### ISSUE TITLE
bug: notificationActionPerformed not triggered on iOS when application was initially killed

### ISSUE THREAD

**Issue by co-dax** [capawesome-team/capacitor-firebase#247] opened 2022-11-10 23:08 UTC
**Plugin(s):**
"@capacitor-firebase/messaging": "^1.1.0",

**Platform(s):**
iOS

**Current behavior:**
When application is initially killed and a notification message (NOT a data message) is sent to an iOS device then notificationActionPerformed is not fired. It does fire if it is a silent message as well (for some reason...)

**Expected behavior:**
When application is initially killed (that is, not started yet) notificationActionPerformed  should be triggered if the message is a notification message

**Steps to reproduce:**

1. KIll applicaition
2. Sent a notification message that is not a silent message
3. Tap notification when it appears in the system tray
4. Event notificationActionPerformed is not triggered

**Comment by robingenz** [comment] 2022-11-11 07:33
Hi @co-dax,
unfortunately I cannot reproduce this. If I close the app completely (kill) and then send a notification and click on it, the `notificationActionPerformed` listener fires as soon as i add the listener. Please test it again with the latest version (`1.2.0`) .

**Comment by johndoe-glitch** [comment] 2022-11-11 07:51
- [ ] approved

**Comment by co-dax** [comment] 2022-11-14 20:54
Thanks, @robingenz.

It turns out I didn't ask for permissions on iOS. On Android it works out of the box without askin for permission as they are allowed by default.

It might be the case to specify requirement to ask for permission on iOS before awaiting notifications.


Thanks again!

**Comment by robingenz** [comment] 2022-11-14 21:08
In this case I will close this issue.

**Closed by robingenz** 2022-11-14 21:08 UTC
Labels: needs: triage, platform: ios, package: messaging
