### ISSUE TITLE
bug: Can't receive push notification with FCM token when app is in foreground on android

### ISSUE THREAD

**Issue by phucnt31** [capawesome-team/capacitor-firebase#727] opened 2024-09-24 05:23 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

I can't receive push notification with FCM token when app is in foreground on android. I have tested push notification with FCM token and is able to received push notification when the app is in background or foreground.

### Expected behavior

Android should be able to received push notification when app is in background or foreground

### Reproduction

https://github.com/phucnt31/test-firebase-messaging

### Steps to reproduce

- Add your own google-services.json file to android/app
- Click "Generate Token" in the app to generate FCM token
- Add your FCM token to firebase cloud messaging

### Other information

https://capawesome.io/blog/the-push-notifications-guide-for-capacitor/#send-push-notifications-with-firebase

I follow this guide you provided in the document to push notification on app

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/core: 6.1.2

[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-09-24 05:51
You can receive push notifications. However, the Firebase Messaging SDK only displays them in the background on Android. I close this issue as duplicate of #398.

**Closed by robingenz** 2024-09-24 05:51 UTC
Labels: bug/fix, needs: triage

**Comment by phucnt31** [comment] 2024-09-24 06:00
> You can receive push notifications. However, the Firebase Messaging SDK only displays them in the background on Android. I close this issue as duplicate of #398.

Hello, I read the issue you provided so is there a config to display notification in the foreground for Android as well, or it is for iOS only?

**Comment by robingenz** [comment] 2024-09-24 06:26
This is what the feature request is about. Such an option does not yet exist.

**Comment by phucnt31** [comment] 2024-09-24 06:31
Thank you for your reply
