### ISSUE TITLE
feat: add support for Notification Service Extension 

### ISSUE THREAD

**Issue by moh4sa** [capawesome-team/capacitor-firebase#732] opened 2024-10-07 13:42 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

currently `@capacitor-firebase/messaging` does support Notification Service Extension  

### Preferred solution

add support for "Notification Service Extension"

### Alternative options

https://capacitorjs.com/docs/guides/push-notifications-firebase#images-in-push-notifications

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment] 2024-10-07 14:04
I know from https://github.com/capawesome-team/capacitor-firebase/issues/731 that the problem is the Firebase Messaging pod. Have you tried using the same version of the pod that the plugin uses?

Currently this is `~> 10.25`, see https://github.com/capawesome-team/capacitor-firebase/blob/1075c9caf328b1acf670f71b199834a3e14ef9f7/packages/messaging/CapacitorFirebaseMessaging.podspec#L16C38-L16C46.

```diff
target 'pushextension' do
-  pod 'FirebaseMessaging'
+  pod 'FirebaseMessaging', '~> 10.25'
end
```

**Comment by moh4sa** [comment] 2024-10-07 18:30
@robingenz  this is what I got: 
[capacitor] ✖ update ios - failed!
[capacitor] [error] Analyzing dependencies
[capacitor]         [!] CocoaPods could not find compatible versions for pod "Firebase/Messaging~> 10.25":
[capacitor]         In Podfile:
[capacitor]         Firebase/Messaging~> 10.25
[capacitor]         
[capacitor]         None of your spec sources contain a spec satisfying the dependency: `Firebase/Messaging~> 10.25`.

**Comment by robingenz** [comment] 2024-10-07 18:48
How does your Podfile look?

**Comment by robingenz** [comment] 2024-10-07 19:37
You forgot the comma. Please copy the text as I have provided it [here](https://github.com/capawesome-team/capacitor-firebase/issues/732#issuecomment-2397030304).

**Comment by moh4sa** [comment] 2024-10-07 19:47
@robingenz  I got new error `node_modules/@capacitor-firebase/analytics/ios/Plugin/FirebaseAnalytics.swift:4:8 No such module 'FirebaseCore'`

**Comment by robingenz** [comment] 2024-10-08 04:42
This is another error that has already been solved, see: https://github.com/capawesome-team/capacitor-firebase/issues/622. For this reason, I am closing this issue as resolved.

**Closed by robingenz** 2024-10-08 04:42 UTC
Labels: feature, needs: triage, platform: ios, package: messaging

**Comment by moh4sa** [comment] 2024-10-08 07:00
@robingenz  Multiple commands produce `'/Users/xx/Library/Developer/Xcode/DerivedData/App-ezouattdyjhpmjfmuuwbpceeevmy/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Privacy.bundle'

Showing All Messages
Target 'GoogleUtilities-54d832b6-GoogleUtilities_Privacy' (project 'Pods') has create directory command with output '/Users/mohdalshehri/Library/Developer/Xcode/DerivedData/App-ezouattdyjhpmjfmuuwbpceeevmy/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Privacy.bundle'


Showing All Messages
Target 'GoogleUtilities-7cacef58-GoogleUtilities_Privacy' (project 'Pods') has create directory command with output '/Users/mohdalshehri/Library/Developer/Xcode/DerivedData/App-ezouattdyjhpmjfmuuwbpceeevmy/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities_Privacy.bundle'`


 this is the main issue I am facing since #731

**Comment by robingenz** [comment] 2024-10-08 07:58
Do you have the full error message? These are just normal log outputs.

---

The error you mentioned in #731 seems to be a different one:

> Target 'GoogleUtilities-7cacef58' (project 'Pods') has create directory command with output '/Users/mohdalshehri/Library/Developer/Xcode/DerivedData/App-ezouattdyjhpmjfmuuwbpceeevmy/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'

**Comment by moh4sa** [comment] 2024-10-08 08:01
here is a screenshot of the full error:
<img width="1093" alt="Screenshot 2024-10-08 at 11 01 14 AM" src="https://github.com/user-attachments/assets/b68611c1-4b9a-4c66-a6c8-d1859f1b1375">

**Comment by robingenz** [comment] 2024-10-08 08:22
Remove the following code from your `Podfile`: 

```
target 'pushextension' do
  pod 'FirebaseMessaging'
end
```

Now sync your Capacitor project (`npy cap sync`) and try it again.

**Comment by moh4sa** [comment] 2024-10-08 08:41
@robingenz but this is needed for push notification  service extension otherwise the feature it wont work

**Comment by robingenz** [comment] 2024-10-08 08:56
Have you tested it? The pod is already added by the plugin itself.

**Comment by moh4sa** [comment] 2024-10-08 09:01
yes @robingenz it gives me this error 
<img width="418" alt="Screenshot 2024-10-08 at 12 00 21 PM" src="https://github.com/user-attachments/assets/9deb914b-2e2a-4716-b293-fc827bdf6c08">

**Comment by robingenz** [comment] 2024-10-08 09:42
You use the Capacitor Firebase Messaging plugin from Capawesome, right? You are NOT using the Capacitor Push Notifications plugin.

**Comment by moh4sa** [comment] 2024-10-08 09:47
no Im using the official plugin from capacitor https://capacitorjs.com/docs/guides/push-notifications-firebase#images-in-push-notifications

**Comment by robingenz** [comment] 2024-10-08 09:56
As [already mentioned](https://github.com/capawesome-team/capacitor-firebase/issues/731#issuecomment-2396695675), please use the [Capacitor Firebase Messaging](https://capawesome.io/plugins/firebase/cloud-messaging/) plugin from Capawesome so that there are no conflicts with the SDK version.

**Comment by moh4sa** [comment] 2024-10-08 10:31
I will use it if it supports`Notification Service Extension` but as far as I know it doesn't which is why I created this Feature request to migrate to [Capacitor Firebase Messaging](https://capawesome.io/plugins/firebase/cloud-messaging/) after it support `Notification Service Extension` otherwise I can't use `@capacitor-firebase` do to these conflicts

**Comment by robingenz** [comment] 2024-10-08 10:53
The Notification Service Extension should already work with `@capacitor-firebase/messaging` as this is a feature of the Firebase Messaging SDK (and not the plugin). There are just no docs for it. If you swap the plugins and [remove the code block](https://github.com/capawesome-team/capacitor-firebase/issues/732?notification_referrer_id=NT_kwDOANN0ibQxMjc1MDQzMDEzNjoxMzg1NzkyOQ#issuecomment-2399182941) from the `Pdofile`, it should work.

**Comment by moh4sa** [comment] 2024-10-08 12:46
@robingenz  I've tried it, but it gives me the same error as before.

> yes @robingenz it gives me this error <img alt="Screenshot 2024-10-08 at 12 00 21 PM" width="418" src="https://private-user-images.githubusercontent.com/28048386/374486667-9deb914b-2e2a-4716-b293-fc827bdf6c08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTAwMjIsIm5iZiI6MTcyODM4OTcyMiwicGF0aCI6Ii8yODA0ODM4Ni8zNzQ0ODY2NjctOWRlYjkxNGItMmUyYS00NzE2LWIyOTMtZmM4MjdiZGY2YzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEyMTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ODExOWE3ZjE4ZGY1ZGEzZjhkN2EzZWU1YjE1MTFmZjZmZTkyZWQzNDdlYjA2ZWVjMDg4MjhkMzg5MmQ1ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ke8To1uMmdI28n15dB4fFXuBQJQ_Sa47A6UtP9cyRao">

**Comment by robingenz** [comment] 2024-10-08 17:40
It seems like your project is a little messed up. It's hard for me to help you via GitHub/Chat. The last thing I can offer you is that you book a consulting hour with me (see [here](https://polar.sh/capawesome-team/products/1c197541-e627-47b9-8c2c-7e4f41e8ea75)) and we look at it together.

**Comment by moh4sa** [comment] 2024-10-08 18:26
@robingenz thanks for the support, it appears its a cocoaPods issue I was able to fix after checking this [issue](https://github.com/CocoaPods/CocoaPods/issues/8206)
