### ISSUE TITLE
bug(app-check): option `debug` is always `true`

### ISSUE THREAD

**Issue by physedo** [capawesome-team/capacitor-firebase#298] opened 2023-01-10 08:23 UTC
**Plugin(s):**

app-check

**Platform(s):**

android.

**Current behavior:**

debug is false and when it is true also
You can still debug it
It works with debug on android
But when I publish it on google play it does not work

**Expected behavior:**

debug:false you can't debug
debug: true you can debug on android
also when sign your app on google play console app check will work 

**Steps to reproduce:**

**Related code:**

```
imports:

import { FirebaseAppCheck, GetTokenResult, InitializeOptions, GetTokenOptions} from '@capacitor-firebase/app-check';
import {  initializeApp, provideFirebaseApp, getApp } from '@angular/fire/app';
import {

  initializeAppCheck,
  CustomProvider,
  provideAppCheck,
  AppCheckToken, 
} from '@angular/fire/app-check';
``

app.module.ts:
`

provideAppCheck(  () => {
      const options: InitializeOptions = {
        debug: false,
        isTokenAutoRefreshEnabled: true
      };
     FirebaseAppCheck.initialize(options);
      const androidprovider = new CustomProvider({
      
        getToken (): Promise<any> {
         
          return   FirebaseAppCheck.getToken();
        },
      });


      const app = getApp();
    return initializeAppCheck(app, {provider:androidprovider})
  }
    ),
```

**Other information:**

**Capacitor doctor:**

💊   Capacitor Doctor  💊 

Latest Dependencies:

 

```
 @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
```

**Comment by robingenz** [comment] 2023-05-02 18:44
Thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by physedo** [comment] 2023-05-02 19:33
How to make it Work with AngularFire?
debug works both with true or false.
Appcheck doesn't work when you do internal test on google play console.
Maybe Ionic or Capicator? Problem

> Thank you for your request. Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by robingenz** [comment] 2023-05-13 07:58
> How to make it Work with AngularFire?

It should work like that (NOT tested):

```ts
import { FirebaseAppCheck } from '@capacitor-firebase/app-check';
import { provideFirebaseApp, initializeApp } from '@angular/fire/app';
import { getAppCheck, provideAppCheck } from '@angular/fire/app-check';

@NgModule({
  imports: [
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAppCheck(() => initializeAppCheck(getApp(), {
        provider: new CustomProvider({
	        getToken: () => {
	            return FirebaseAppCheck.getToken();
	        },
	    })
      })),
  ]
})
```

See also: https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/app-check/docs/firebase-js-sdk.md

>  Appcheck doesn't work when you do internal test on google play console.

I don't have a project right now where I can test this. I guess in this case your SHA-256 fingerprint you use for the internal test is not correct.

**Comment by physedo** [comment] 2023-05-13 13:54
I make it work on homepage not in  internal test android. And my code above works. Your code is not working. SHA-256 is not problem. Maybe  this plugin or capicator @robingenz

**Comment by robingenz** [comment] 2023-05-13 14:21
If it basically works only in the internal test track not, then it is not a problem with capacitor or the plugin but the configuration.

**Comment by physedo** [comment] 2023-05-13 15:11
Only issues @robingenz I been working with ionic / capacitor tools a long time. There always issues you can't fix

**Comment by robingenz** [comment] 2023-05-13 17:14
I have never had a problem with Capacitor that could not be solved. 

I close this issue because there is no minimal, reproducible example.

**Closed** 2023-05-13 17:14 UTC
Labels: platform: android, needs: reproduction, needs: triage, package: app-check

**Comment by physedo** [comment] 2023-05-13 21:35
I think you are filling a hole but at the same time digging a new one @robingenz

**Comment by EmreAkkoc** [comment] 2023-05-27 15:59
> > How to make it Work with AngularFire?
> 
> It should work like that (NOT tested):
> 
> ```ts
> import { FirebaseAppCheck } from '@capacitor-firebase/app-check';
> import { provideFirebaseApp, initializeApp } from '@angular/fire/app';
> import { getAppCheck, provideAppCheck } from '@angular/fire/app-check';
> 
> @NgModule({
>   imports: [
>     provideFirebaseApp(() => initializeApp(environment.firebase)),
>     provideAppCheck(() => initializeAppCheck(getApp(), {
>         provider: new CustomProvider({
> 	        getToken: () => {
> 	            return FirebaseAppCheck.getToken();
> 	        },
> 	    })
>       })),
>   ]
> })
> ```
> 
> See also: https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/app-check/docs/firebase-js-sdk.md
> 
> > Appcheck doesn't work when you do internal test on google play console.
> 
> I don't have a project right now where I can test this. I guess in this case your SHA-256 fingerprint you use for the internal test is not correct.

that example gives type error how can I solve it
`Type '() => Promise<GetTokenResult>' is not assignable to type '() => Promise<AppCheckToken>'.
  Type 'Promise<GetTokenResult>' is not assignable to type 'Promise<AppCheckToken>'.
    Type 'GetTokenResult' is not assignable to type 'AppCheckToken'.
      Property 'expireTimeMillis' is optional in type 'GetTokenResult' but required in type 'AppCheckToken'.ts(2322)
app-check-public.d.ts(102, 5): The expected type comes from property 'getToken' which is declared here on type 'CustomProviderOptions'`
