### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by DeveloperAdam-github** [capawesome-team/capacitor-firebase#183] opened 2022-08-21 13:20 UTC
**Plugin(s):**
  plugins: {
    FirebaseAuthentication: {
      skipNativeAuth: false,
      providers: ['apple.com', 'facebook.com', 'google.com'],
    },
  },

**Platform(s):**
iOS

**Current behavior:**
Seems the firebase app is never configured, I have followed set up instructions and still get this everytime.

**Expected behavior:**

**Steps to reproduce:**
Followed the steps to, using a Vue3 app

**Related code:**
2022-08-21 14:05:10.948014+0100 App[41577:776116] 9.1.0 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌

**Comment by DeveloperAdam-github** [comment] 2022-08-21 13:28
Had to add FirebaseApp.configure() inside the first func application(_application function inside AppDelegate, maybe could add this into the instructions?

However the error has gone now!

**Comment by robingenz** [comment] 2022-08-21 15:08
This message should only be a warning and no error message.
`FirebaseApp.configure()` gets already called by the plugin but not soon enough, so the message appears.
Everything should still work.

I close this as a duplicate of #142.

**Closed by robingenz** 2022-08-21 15:08 UTC
Labels: duplicate
