### ISSUE TITLE
bug: Dependency Conflict: @capacitor-firebase/authentication@6.2.0 Incompatible with firebase@11.0.2

### ISSUE THREAD

**Issue by njvb** [capawesome-team/capacitor-firebase#764] opened 2024-11-29 10:35 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

@capacitor-firebase/authentication@6.2.0

### Platform(s)

- [ ] Android
- [ ] iOS
- [X] Web

### Current behavior

@capacitor-firebase/authentication@6.2.0 requires a peer optional dependency of firebase@^10.9.0, however the latest version is 11.

### Expected behavior

No npm dependancy errors

### Reproduction

n/a

### Steps to reproduce

npm update on any outdated packages will throw an error because of this dependancy need

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-11-29 11:11
Closed as duplicate of #759 and #762. Next time, please follow the bug reporting guidelines and search for existing issues first.

**Closed by robingenz** 2024-11-29 11:11 UTC
Labels: bug/fix, needs: triage
