### ISSUE TITLE
bug: unable to archive ios when used with push notifications plugin 

### ISSUE THREAD

**Issue by moh4sa** [capawesome-team/capacitor-firebase#731] opened 2024-10-06 11:51 UTC
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

unable to archive the ios build due to conflict on cocopods' dependencies 
error is : 
Target 'GoogleUtilities-7cacef58' (project 'Pods') has create directory command with output '/Users/mohdalshehri/Library/Developer/Xcode/DerivedData/App-ezouattdyjhpmjfmuuwbpceeevmy/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GoogleUtilities.framework'
\

I believe this happened when you are using the @capacitor/push-notifications plugin and trying to add @capacitor-firebase/analytics 

### Expected behavior

to be able to archive the ios app normally

### Reproduction

https://github.com/

### Steps to reproduce

1. add @capacitor/push-notifications as per the ionic guide https://capacitorjs.com/docs/guides/push-notifications-firebase
2. add a Notification Service Extension as well
3. add  @capacitor-firebase/analytics 
4. try to archive the build

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-10-06 11:53
Thank you for your request. Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by moh4sa** [comment] 2024-10-07 06:39
@robingenz  here is a link to repo https://github.com/moh4sa/firebaseAnalytics

**Comment by robingenz** [comment] 2024-10-07 08:13
Please make sure that you follow the [installation instructions](https://capawesome.io/plugins/firebase/analytics/#ios) exactly. The following import is incorrect: https://github.com/moh4sa/firebaseAnalytics/blob/45787627e527d45149358b5ced74928c589cde10/ios/App/Podfile#L26

**Comment by moh4sa** [comment] 2024-10-07 10:37
@robingenz  this as per the documentation https://capawesome.io/plugins/firebase/analytics/#:~:text=App%27%20do%0Acapacitor_pods-,%23%20Add%20your%20Pods%20here,-%2B%20%20pod%20%27CapacitorFirebaseAnalytics/Analytics is it outdated or wrong?

**Comment by robingenz** [comment] 2024-10-07 11:15
You have this:

```
pod 'CapacitorFirebaseAnalytics', :path => '../../node_modules/@capacitor-firebase/analytics'
```

The documentation states that:

```
pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'
```

Diff:

```diff
- pod 'CapacitorFirebaseAnalytics', :path => '../../node_modules/@capacitor-firebase/analytics'
+ pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'
```

**Comment by moh4sa** [comment] 2024-10-07 11:22
@robingenz  sorry about that I've updated the repo

**Comment by robingenz** [comment] 2024-10-07 11:29
Please let me know if your issue is resolved.

**Comment by moh4sa** [comment] 2024-10-07 11:33
@robingenz it's not as its not related to this mistake

**Comment by robingenz** [comment] 2024-10-07 11:43
Okay, next on the list would be replacing the `@capacitor/push-notifications` plugin with `@capacitor-firebase/messaging` to ensure that the Firebase SDK versions used are compatible. Please update your repository, test it and let me know if it helped.

**Comment by moh4sa** [comment] 2024-10-07 11:48
@robingenz  does it support push notifications with an image using ios Notification Service Extension same as `@capacitor/push-notifications` as I don't see it mentioned in the docs

**Comment by robingenz** [comment] 2024-10-07 11:56
This should be supported as this is supposed to be the task of the Firebase SDK. Do you have an example? Where is it mentioned in the `@capacitor/push-notifications` docs?

**Comment by moh4sa** [comment] 2024-10-07 11:59
Yes! here is it https://capacitorjs.com/docs/guides/push-notifications-firebase#images-in-push-notifications:~:text=iOS%20requires%20a%20Notification%20Service%20Extension%20to%20be%20added%20to%20your%20project%20in%20order%20to%20display%20images%20in%20push%20notifications.

**Comment by robingenz** [comment] 2024-10-07 12:01
Yes, this should work. Please give it a try and let me know if you encounter any issue.

**Comment by robingenz** [comment] 2024-10-07 12:03
But strictly speaking, this is a separate issue. It is therefore best to remove the `@capacitor/push-notifications` plugin and test whether this issue is resolved. You can then create a feature request for the Notification Service Extension and we will make sure that it works.

**Comment by robingenz** [comment] 2024-10-07 12:42
Please remove the `@capacitor/push-notifications` plugin and the `Firebase/Messaging` pod and test whether this issue is resolved.

**Comment by moh4sa** [comment] 2024-10-07 13:39
@robingenz  This solves the issue, which means there is a conflict in dependencies between `@capacitor/push-notifications`, `Firebase/Messaging`, and `@capacitor-firebase/messaging`. They can't be used together. Furthermore, I can just switch to `@capacitor-firebase/messaging` as it does not support "Notification Service Extension."

**Comment by moh4sa** [comment] 2024-10-07 13:43
Ive submited [feature request](https://github.com/capawesome-team/capacitor-firebase/issues/732) for  Notification Service Extension

**Comment by robingenz** [comment] 2024-10-07 14:04
I am closing this issue because it is not a bug but a feature request (see #732).

**Closed by robingenz** 2024-10-07 14:04 UTC
Labels: bug/fix, needs: reproduction, needs: triage, platform: ios, package: analytics
