### ISSUE TITLE
bug: Does not return collection data when more than one query constraint

### ISSUE THREAD

**Issue by Tsquared86** [capawesome-team/capacitor-firebase#540] opened 2024-01-07 02:52 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

Latest

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

I am returning data from a collection and using the query constraint "and" to compare multiple fields. This works fine on all platforms, but when on android this does not return data. 

### Expected behavior

IT should work like on web and iOS returning data.

### Reproduction

https://github.com/tsquared86

### Steps to reproduce

try to do a query of a collection with an and comparison of 2 or more constraints

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by orestis-z** [comment] 2024-01-14 16:49
+1

**Comment by jwuliger** [comment] 2024-01-30 13:44
Hello, I would like to chime in here. I have a query issue on Android that has me running in circles. In my Ionic/Capacitor Angular application for Android, I have a method to load collection data by the user who is signed in.

```
    async loadConversations(userId: string) {
        try {
            const queryConstraints = [
                {
                    type: 'where',
                    fieldPath: 'userId',
                    opStr: '==',
                    value: userId
                },
                {
                    type: 'orderBy',
                    fieldPath: 'timestamp',
                    directionStr: 'desc'
                }
            ];

            const snapshots = await this.firestoreService.getCollection(
                'conversations',
                queryConstraints
            );
            this.conversations = snapshots.map((doc) => {
                const data = doc.data as Partial<Conversation>;
                return { id: doc.id, ...data };
            });
        } catch (error) {
            console.error('Error loading conversations:', error);
        }
    }
 ```
The problem started when I added 'where' query. When run in the browser it first asked me to create a composite query index in Firebase to run the query. Once I added the new index, I saw the data load on that page.

When I run the same code on my Android Phone I get this error:

```
Error: Attempt to invoke interface method 'com.google.firebase.firestore.Query io.capawesome.capacitorjs.plugins.firebase.firestore.interfaces.QueryNonFilterConstraint.toQuery(com.google.firebase.firestore.Query, com.google.firebase.firestore.FirebaseFirestore)' on a null object reference
```

the 'getCollection()' method is in a service and the method is:

```
    async getCollection(reference: string, queryConstraints: any[]) {
        const { snapshots } = await FirebaseFirestore.getCollection({
            reference,
            queryConstraints
        });
        return snapshots;
    }
```

I have no idea what the null object reference could be.

Here is what my index looks like from the Firebase Console

![2024-01-30_8-41-36](https://github.com/capawesome-team/capacitor-firebase/assets/14036569/95365343-6f08-4305-9f7c-aedd2970d753)

Any help would be greatly appreciated. Thanks for your time. Please let me know if I can provide anything further. This is a private code base so I can't link the repo.

**Comment by robingenz** [comment] 2024-01-30 13:56
I will probably work on the Firestore issues next week.

**Comment by jwuliger** [comment] 2024-02-11 18:06
Update:

I modified ```FirebaseFirestore.java > getCollection()``` method. I added a null check for the ```queryConstraint``` 

Here is the method that works on my Android Device:


```
    public void getCollection(@NonNull GetCollectionOptions options, @NonNull NonEmptyResultCallback callback) throws Exception {
        String reference = options.getReference();
        QueryCompositeFilterConstraint compositeFilter = options.getCompositeFilter();
        QueryNonFilterConstraint[] queryConstraints = options.getQueryConstraints();

        Query query = this.firestoreInstance.collection(reference);
        if (compositeFilter != null) {
            Filter filter = compositeFilter.toFilter();
            assert filter != null;
            query = query.where(filter);
        }
        for (QueryNonFilterConstraint queryConstraint : queryConstraints) {
            if (queryConstraint != null) { // Add this null check
                query = queryConstraint.toQuery(query, this.firestoreInstance);
            } else {
                // Optionally handle the null case, e.g., log an error
                Log.e("FirebaseFirestore", "Encountered null QueryNonFilterConstraint");
            }
        }
        query
            .get()
            .addOnSuccessListener(
                querySnapshot -> {
                    GetCollectionResult result = new GetCollectionResult(querySnapshot);
                    callback.success(result);
                }
            )
            .addOnFailureListener(callback::error);
    }
```

I hope this helps.

**Comment by robingenz** [comment] 2024-02-14 12:50
@Tsquared86 I close this issue as duplicate of #554.

@jwuliger Please create a new issue and provide some code to reproduce this issue. I do not know the implementation of your `firestoreService`.

**Closed by robingenz** 2024-02-14 12:50 UTC
Labels: platform: android, bug/fix, needs: triage, package: firestore
