### ISSUE TITLE
bug: FirebaseAuthentication linkWithEmailAndPassword

### ISSUE THREAD

**Issue by jakubforman** [capawesome-team/capacitor-firebase#315] opened 2023-02-10 14:39 UTC
**Plugin(s):**
@capacitor-firebase/authentication

**Platform(s):**
iOS - ❌
Android - ❓not tested yet
web - ✅

**Current behavior:**
⚡️  To Native ->  AdMob hideBanner 67407460
ERROR MESSAGE:  {"errorMessage":"[ERROR_PROVIDER_ALREADY_LINKED] - User can only be linked to one identity for the given provider.","message":"[ERROR_PROVIDER_ALREADY_LINKED] - User can only be linked to one identity for the given provider."}
2023-02-10 15:25:01.259909+0100 App[34587:9490117] AdMob: find subView for hideBanner
⚡️  [error] - {"errorMessage":"[ERROR_PROVIDER_ALREADY_LINKED] - User can only be linked to one identity for the given provider.","message":"[ERROR_PROVIDER_ALREADY_LINKED] - User can only be linked to one identity for the given provider."}

**Expected behavior:**
If the user logged in only on Google Provider and then the user wants to link an existing account to an email, then needs to link the email, not send an error.

**Steps to reproduce:**
1. Login with Google (or another provider)
2. Run `linkWithEmailAndPassword` and see the error

**Related code:**

```typescript
// google login
async googleLogin(): Promise<UserCredential> {
        // 1. Create credentials on the native layer
        const result = await FirebaseAuthentication.signInWithGoogle({skipNativeAuth: true});
        // 2. Sign in on the web layer using the access token
        const credential = GoogleAuthProvider.credential(result.credential?.idToken);
        const auth = getAuth();
        // 3. Return web layer result
        return await signInWithCredential(auth, credential);
    }


// Link email
 async linkWithPassword(email: string, password: string): Promise<User> {
        // 1. Link account on native layer
        const result = await FirebaseAuthentication.linkWithEmailAndPassword({
            email: email,
            password: password
        });
        // 2. Get web layer auth
        const auth = getAuth();
        await auth.currentUser.reload();
        this.userSubject.next(auth.currentUser);
        return auth.currentUser;
    }
```

**Other information:**

I use `AngularFire`, but this package is not a problem. Same behavior if I use the standard Firebase NPM package.
- Also use Firebase Emulator
- Device: Emulator iOS 16.2. iPhone 14 Pro
- Environment: Mac mini M1 16 GB RAM

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/ios: 4.6.3
  @capacitor/android: 4.6.3

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

**Comment by robingenz** [comment] 2023-02-10 18:35
This error is caused by Firebase itself and not the plugin. For this reason i am closing this issue.
Please take a look at these two SO answers:
1. https://stackoverflow.com/a/46138349/6731412
2. https://stackoverflow.com/a/48813632/6731412

**Closed by robingenz** 2023-02-10 18:35 UTC
Labels: needs: triage, package: authentication

**Comment by robingenz** [comment] 2023-02-10 18:41
Apart from that, what you have in mind does not work like that. If you use `skipNativeAuth` for the sign-in, then the user is not logged in on the native layer. This means that `FirebaseAuthentication.linkWithEmailAndPassword(...)` (which is native) does not work, because there is no user logged in to which an email and password can be linked. You have to use the `linkWithEmailAndPassword(...)` method from the JS SDK directly instead.
