### ISSUE TITLE
bug: Different Device Check Providers value in Different Projects

### ISSUE THREAD

**Issue by TamilselvanMariyappan** [capawesome-team/capacitor-firebase#451] opened 2023-10-10 07:09 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [X] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

{
"provider": "device_check_app_attest",
}

### Expected behavior

{
"provider": "device_check_device_identification"
}

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

Once login we got the JWT response by using "https://jwt.io/" we debug we got above provider response

### Capacitor doctor

Latest Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

Installed Dependencies:

  @capacitor/cli: 5.2.2
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-10-10 07:33
> I understand that incomplete issues (e.g. without reproduction) are closed.

I am closing this issue because not enough information has been provided and no reproduction exists.

**Closed by robingenz** 2023-10-10 07:33 UTC
Labels: bug/fix, needs: triage

**Comment by TamilselvanMariyappan** [comment] 2023-11-03 11:51
@robingenz     In one of our projects, we encountered an issue with DeviceCheck where we found that the provider we received was` "device_check_app_attest."` However, in another project where DeviceCheck is working correctly, the provider appears as `"device_check_device_identification."`
The project facing the DeviceCheck issue is using Angular version 13.4.0 and "@capacitor-firebase/app-check" version "^5.1.0."
As we investigate further, we've noticed that the JWT response has the structure: "provider": `"device_check_app_attest."`
We are experiencing this behavior in Ios devices.
Below we attached JWT response
`//Expected behavior

{ "sub": "1:************06:ios:3b262cd82***********",
 "aud": ["projects/85********",   
 "projects/ABC"], 
 "provider": "device_check_device_identification", 
 "iss": "https://firebaseappcheck.googleapis.com/*********", 
 "exp": 1695284564, 
 "iat": 1695280964, 
 "jti": "G6vqvRPv**********************60tRmR1***"
},


// Current behavior
{
    "sub": "1:***********06:ios:1b3f479e7**************",
    "aud": [
      "projects/85*********",
      "projects/ABC"
    ],
    "provider": "device_check_app_attest",
    "iss": "https://firebaseappcheck.googleapis.com/***********",
    "exp": 1695293981,
    "iat": 1695290381,
    "jti": "EBdv4gM8***************************i1j1lMX***"
  }`

**Comment by robingenz** [comment] 2023-11-03 12:36
Device Check is only supported up to iOS 13. From iOS 14 you have to use App Attest.

**Comment by TamilselvanMariyappan** [comment] 2023-11-06 11:20
The Device Check error we found out under iOS 13 devices
