### ISSUE TITLE
bug: No such module 'FirebaseCore' with just the Analytics plugin

### ISSUE THREAD

**Issue by TomDoesb** [capawesome-team/capacitor-firebase#622] opened 2024-04-29 08:32 UTC
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.0.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

I've added the analytics package to my project following [the readme](https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/analytics/README.md) and updated the pod file as described.

When building the project in Xcode it fails with `No such module 'FirebaseCore'` I could reproduce this error in a minimal reproducible example. The link is added below.

XCode version: 15.3 (15E204a)

Ive checked related closed issues but solutions described there did not resolve the issue.

### Expected behavior

I expected a successful build

### Reproduction

https://github.com/TomDoesb/.capacitor-app

### Steps to reproduce

1. Open the repo in xcode
2. Build
3. Behold the `No such module 'FirebaseCore'`

### Capacitor doctor

npx cap doctor
[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/android: 6.0.0
  @capacitor/ios: 6.0.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 6.0.0
  @capacitor/core: 6.0.0
  @capacitor/ios: 6.0.0

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-04-29 14:54
Please follow the installation instructions for iOS correctly, see [iOS](https://capawesome.io/plugins/firebase/analytics/#ios):

```
Add the `CapacitorFirebaseAnalytics/Analytics` pod to your `Podfile` (usually `ios/App/Podfile`):

	```diff
	target 'App' do
	capacitor_pods
	# Add your Pods here
	+  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'
	end
	```

```

**Comment by TomDoesb** [comment] 2024-04-30 06:45
https://github.com/TomDoesb/.capacitor-app/blob/main/ios/App/Podfile

Did you check? Its there..

**Comment by robingenz** [comment] 2024-04-30 08:50
I think most people just copy the line. Im closing this issue as resolved.

**Closed by robingenz** 2024-04-30 08:50 UTC
Labels: bug/fix, needs: triage, platform: ios, package: analytics

**Comment by tomkortjak** [comment] 2024-05-02 08:21
The pod file shouldn't really be changed manually, a simple command like npx cap sync will overwrite these changes every time. That's how I just ran into this bug.

**Comment by robingenz** [comment] 2024-05-02 08:37
@TomDoesb That's not correct. The `npx cap sync` command only overwrites the `def capacitor_pods` section. That's why the pod must be added to the `target 'App' do` section. This is not a bug. That's just the way how you configure the pods.

**Comment by tomkortjak** [comment] 2024-05-02 08:43
Yes, you're right. Skipped right over that part of the documentation, sorry! 😅
