### ISSUE TITLE
bug: SignInWithGoogle is not working on Android. It works on iOS and web.

### ISSUE THREAD

**Issue by iampapaisarkar** [capawesome-team/capacitor-firebase#676] opened 2024-07-13 10:10 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.0.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When I try to sign in with Google, it shows the Google accounts popup. After selecting an account, I get an error message that only shows ':10', and my application reloads automatically.

Here is my code:
 ```diff
loginWithGoogleSDK() {
      this.googleLoading = true
      signInWithGoogle()
        .then(({ credential }) => {
          const credentialToLogin = GoogleAuthProvider.credential(
            credential?.idToken
          )
          signInWithCredential(this.getAuth(), credentialToLogin)
            .then(({ user }) => {
              this.getIdToken()
                .then((token) => {
                  const oneHourInMilliseconds = 3600000 // 1 hour in milliseconds
                  // Handle successful login
                  this.token = token
                  this.callbackFirebaseSuccessResponse(
                    'post',
                    '/check-oauth-linked-account',
                    {
                      access_token: token,
                      expire_at: user.metadata.creationTime + oneHourInMilliseconds,
                      provider_id: 'google.com',
                      uid: this.getProviderDetailsByProviderID(
                        user.providerData,
                        'google.com'
                      ).uid,
                      device_token: this.getLocal('deviceToken'),
                      device_type: this.platformType,
                      device_id: this.device.id,
                      device_model: this.device.model
                    }
                  )
                })
            })
            .catch((error) => {
              // Handle login errors
              console.error(error)
              if (error.code === 'auth/multi-factor-auth-required') {
                this.verifyMfa = true
                this.mfaError = error
                this.verifyRecaptchaAndSendCode()
              } else if (error.code !== 'auth/popup-closed-by-user') {
                this.errorNotify(this.formattedFirebaseError(error))
              }
              this.googleLoading = false
              alert(JSON.stringify(error))
            })
        })
        .catch((error) => {
          // Handle login errors
          console.error(error)
          alert(JSON.stringify(error))
          if (error.code === 'auth/multi-factor-auth-required') {
            this.verifyMfa = true
            this.mfaError = error
            this.verifyRecaptchaAndSendCode()
          } else if (error.code !== 'auth/popup-closed-by-user') {
            this.errorNotify(this.formattedFirebaseError(error))
          }
          this.googleLoading = false
        })
    }
 ```
![image](https://github.com/user-attachments/assets/7fd38be5-56a2-482d-a0e8-91667cd47245)

### Expected behavior

When I use sign-in with Google, it should sign in successfully.

### Reproduction

https://github.com/capawesome-team/.capacitor-app

### Steps to reproduce

Can't share project

### Capacitor doctor

![image](https://github.com/user-attachments/assets/5d6ad0de-0d53-4c14-b048-7a3a4e18c006)

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-07-13 10:15
Please follow the [bug report guidelines](https://capawesome.io/contributing/bug-reports/) and search for existing issues. I close this issue as duplicate of #220.

**Closed by robingenz** 2024-07-13 10:15 UTC
Labels: bug/fix, needs: triage

**Comment by tepaseointenso** [comment] 2024-08-29 23:44
I'm having the same issue
