### ISSUE TITLE
bug: Firestore arrayUnion

### ISSUE THREAD

**Issue by jongbonga** [capawesome-team/capacitor-firebase#458] opened 2023-10-15 02:41 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [X] iOS
- [X] Web

### Current behavior

When I use `arrayUnion` in `setDocument` on the web this is what I get
<img width="438" alt="Screenshot 2023-10-15 at 05 25 52" src="https://github.com/capawesome-team/capacitor-firebase/assets/12111716/dded2791-e14a-4457-ba64-b4448c8a854e">
The result is perfect and I tested extensively and I'm happy with the result.

But when used on iOS this is the result
<img width="329" alt="Screenshot 2023-10-15 at 05 25 30" src="https://github.com/capawesome-team/capacitor-firebase/assets/12111716/739fa6be-40a0-4fac-a2f7-9fe17428fa3f">

` _methodName` & `wu` are added and I'm not sure why...

My code is fairly simple, maybe because `arrayUnion` is imported from `firebase/firestore`

```
import { FirebaseFirestore } from '@capacitor-firebase/firestore';
import { arrayUnion, Timestamp } from 'firebase/firestore';

const messages = userId
  ? arrayUnion({
      id: nanoid(8),
      text,
      timestamp: Timestamp.now(),
      userId
    })
  : [];

await FirebaseFirestore.setDocument({
  reference: `trips/${tripId}/chats/${stopId}`,
  data: { messages },
  merge: true
});
```

### Expected behavior

I'd would expect the web & native result to match

### Reproduction

n/a

### Steps to reproduce

```
import { FirebaseFirestore } from '@capacitor-firebase/firestore';
import { arrayUnion, Timestamp } from 'firebase/firestore';

const messages = userId
  ? arrayUnion({
      id: nanoid(8),
      text: 'test',
      timestamp: Timestamp.now(),
      userId
    })
  : [];

await FirebaseFirestore.setDocument({
  reference: `trips/${tripId}/chats/${stopId}`,
  data: { messages },
  merge: true
});
```

### Capacitor doctor

```
❯ npx capacitor doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0
  @capacitor/core: 5.5.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-10-15 06:50
Thank you for your request.
arrayUnion is not yet supported.
I close this issue as duplicate of #443.

**Closed** 2023-10-15 06:51 UTC
Labels: duplicate, bug/fix, package: firestore
