### ISSUE TITLE
bug: signInWithTwitter and skipNativeAuth=true does not return credentials (accesstoken and secret)

### ISSUE THREAD

**Issue by emilkaiser** [capawesome-team/capacitor-firebase#116] opened 2022-06-16 09:15 UTC
**Plugin(s):**
JS:
"firebase": "9.8.2"
"@capacitor-firebase/authentication": "0.3.2"
iOS:
@capacitor-firebase/authentication@0.3.1
<img width="421" alt="Skärmavbild 2022-06-16 kl  10 38 13" src="https://user-images.githubusercontent.com/481986/174029657-337d4f7d-6c8b-431a-a3a3-28112fe17891.png">

**Platform(s):**
iOS + web

**Current behavior:**
<img width="1055" alt="Skärmavbild 2022-06-16 kl  10 31 00" src="https://user-images.githubusercontent.com/481986/174029702-7fce4b24-1810-4204-97f9-485a44b8af15.png">
![IMG_D0D1690CCC8C-1](https://user-images.githubusercontent.com/481986/174035386-24552926-fffc-4cc1-86a6-71d1c9761134.jpeg)

The result from `await FirebaseAuthentication.signInWithTwitter()` is missing the expected `accessToken` and `secret` when `skipNativeAuth=true` is set.

**Expected behavior:**
`await FirebaseAuthentication.signInWithTwitter()` should return credentials to be used to sign in on web layer with Firebase JS SDK.

**Steps to reproduce:**
Use example project found here [https://github.com/robingenz/capacitor-firebase-authentication-demo](https://github.com/robingenz/capacitor-firebase-authentication-demo) and steps here [https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md](https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md) and here [https://github.com/robingenz/capacitor-firebase/issues/99](https://github.com/robingenz/capacitor-firebase/issues/99).

**Related code:**
I did this: [https://github.com/robingenz/capacitor-firebase/issues/99#issuecomment-1156250009](https://github.com/robingenz/capacitor-firebase/issues/99#issuecomment-1156250009) and also made sure that `skipNativeAuth=true` was set and propagated to native layer (by default the example app did not correctly set the ios config, had to change manually).
<img width="570" alt="Skärmavbild 2022-06-16 kl  10 31 47" src="https://user-images.githubusercontent.com/481986/174029511-d7d61e6d-4ade-4b03-a251-57e97a3d328f.png">
<img width="467" alt="Skärmavbild 2022-06-16 kl  10 32 04" src="https://user-images.githubusercontent.com/481986/174029542-13fa8921-634d-454c-8b89-2295128b8184.png">

**Notice:**
I also had to add `skipNativeAuth=true` to `ios/App/App/capacitor.config.json` since it not got copied there when building.

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/android: 3.5.1
  @capacitor/ios: 3.5.1
  @capacitor/core: 3.5.1

[success] iOS looking great! 👌
[error] app/src/main/assets/public directory is missing in android
```

**Comment by robingenz** [comment] 2022-06-16 09:44
Hi @emilkaiser,
thank you for this detailed issue!
I will have a look at it as soon as possible.

**Comment by robingenz** [comment] 2022-06-16 09:45
@emilkaiser Quick question first: Does it work on Android or have you not tested it there?

**Comment by emilkaiser** [comment] 2022-06-16 09:47
Sorry, I have not tested Android. I _think_ my (Android-)colleague did have the same issue, but not sure.

**Comment by bastifix** [comment] 2022-06-21 21:43
I'm trying to do the same with Microsoft as AuthProvider, but it seems to be the same problem. (only tried on iOS)
(Microsoft and Twitter are both not in the [examples](https://github.com/robingenz/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md): is it the right way to implement it?)

**Comment by braincomb** [comment] 2022-07-13 20:01
+1. Having same `(auth/argument-error)` error with Twitter sign in.

**Comment by robingenz** [comment] 2022-07-15 18:26
So i could reproduce the issue on iOS but not on Android.
The Firebase Android SDK requests the access token **before** signing in using the generated OAuthCredential.
https://github.com/capawesome-team/capacitor-firebase/blob/4a0e4df7275dfa080d09ac4b3fa9e43448158f9f/packages/authentication/android/src/main/java/dev/robingenz/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java#L341
The Firebase iOS SDK seems to request the access token **after** signing using the generated OAuthCredential.
https://github.com/capawesome-team/capacitor-firebase/blob/4a0e4df7275dfa080d09ac4b3fa9e43448158f9f/packages/authentication/ios/Plugin/FirebaseAuthentication.swift#L235

This is related to https://github.com/firebase/firebase-ios-sdk/issues/9878.

According to the Firebase documentation (see [Step 5](https://firebase.google.com/docs/auth/ios/twitter-login#handle_the_sign-in_flow_with_the_firebase_sdk)), this is intended for iOS and therefore not a bug. So it seems that this is not possible under iOS.

I see only two options here:
1. Make a feature request in the Firebase iOS SDK repo and ask to extend the SDK accordingly.
2. Extend the `skipNativeAuth` option and allow that it could be configured per provider. This would be a separate feature request.

For this reason, I am closing this issue.

**Closed by robingenz** 2022-07-15 18:26 UTC
Labels: needs: triage, package: authentication
