### ISSUE TITLE
bug(authentication): verifyPhoneNumber errors are ignored on iOS

### ISSUE THREAD

**Issue by DmitrySboychakov** [capawesome-team/capacitor-firebase#519] opened 2023-12-13 18:48 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.2.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

In case of error returned by Firebase in `PhoneAuthProvider.provider().verifyPhoneNumber` it getting ignored and `verificationID` sets to empty string which breaks further actions 

### Expected behavior

Error should not be ignored and passed to the `phoneVerificationFailed` listener

### Reproduction

none

### Steps to reproduce

Sometimes firebase could return errors and there no 100% way to reproduce it.

### Capacitor doctor

[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-12-13 20:21
I close this issue as duplicate of #380. I will take a look at your PR.

**Closed by robingenz** 2023-12-13 20:21 UTC
Labels: bug/fix, platform: ios, package: authentication
