### ISSUE TITLE
feat: InApp Messaging

### ISSUE THREAD

**Issue by josuelmm** [capawesome-team/capacitor-firebase#555] opened 2024-02-14 04:06 UTC
### Plugin(s)

- [ ] Analytics
- [X] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

InApp Messaging is not implemented

### Preferred solution

Implement InApp Messaging
https://firebase.google.com/products/in-app-messaging

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment] 2024-02-14 07:19
I close this as duplicate of #129.

**Closed** 2024-02-14 07:19 UTC
Labels: feature, needs: triage
