### ISSUE TITLE
bug: iOS build fails with "No such module 'FirebaseCore'"

### ISSUE THREAD

**Issue by chrisvor** [capawesome-team/capacitor-firebase#182] opened 2022-08-21 07:06 UTC
**Plugin(s):**

Analytics

**Platform(s):**

iOS

**Current behavior:**

 I added the Analytics plugin as per instructions. However when I try to build the iOS app, it fails with "No such module FirebaseCore". Could somebody please help? Production app needing an update.....

**Expected behavior:**

Xcode should build successfully

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2022-08-21 07:48
Did you open the `xcodeproj` file instead of the `xcworkspace` file (see [here](https://stackoverflow.com/a/33946372/6731412))?
Please share all you dependencies (`package.json`).

**Comment by chrisvor** [comment] 2022-08-21 08:14
No I opened the workspace using "ionic cap open ios"....

Package.json dependencies:
"dependencies": {
    "@angular-devkit/schematics-cli": "^0.901.13",
    "@angular/cli": "^14.1.2",
    "@angular/common": "^14.1.2",
    "@angular/core": "^14.1.2",
    "@angular/fire": "^7.4.1",
    "@angular/forms": "^14.1.2",
    "@angular/localize": "^14.1.2",
    "@angular/platform-browser": "^14.1.2",
    "@angular/platform-browser-dynamic": "^14.1.2",
    "@angular/router": "^14.1.2",
    "@awesome-cordova-plugins/core": "^5.44.0",
    "@awesome-cordova-plugins/diagnostic": "^5.44.0",
    "@awesome-cordova-plugins/in-app-browser": "^5.44.0",
    "@capacitor-community/sqlite": "^4.0.0-1",
    "@capacitor-firebase/analytics": "^1.0.0",
    "@capacitor-firebase/authentication": "^1.0.0",
    "@capacitor/android": "^4.1.0",
    "@capacitor/app": "^4.0.1",
    "@capacitor/browser": "^4.0.1",
    "@capacitor/core": "^4.1.0",
    "@capacitor/device": "^4.0.1",
    "@capacitor/filesystem": "^4.0.1",
    "@capacitor/geolocation": "^4.0.1",
    "@capacitor/ios": "^4.1.0",
    "@capacitor/local-notifications": "^4.0.1",
    "@capacitor/network": "^4.0.1",
    "@capacitor/push-notifications": "^4.0.1",
    "@capacitor/splash-screen": "^4.0.1",
    "@capacitor/status-bar": "^4.0.1",
    "@ionic-native/app-rate": "^5.31.1",
    "@ionic-native/app-version": "^5.30.0",
    "@ionic-native/call-number": "^5.30.0",
    "@ionic-native/core": "^5.30.0",
    "@ionic-native/http": "^5.30.0",
    "@ionic-native/in-app-browser": "^5.30.0",
    "@ionic-native/market": "^5.30.0",
    "@ionic-native/native-geocoder": "^5.30.0",
    "@ionic/angular": "^6.2.2",
    "@ionic/storage": "^2.3.1",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@turf/turf": "^5.1.6",
    "@types/google-maps": "^3.2.2",
    "@types/leaflet": "^1.5.19",
    "cordova-plugin-advanced-http": "^3.1.0",
    "cordova-plugin-app-version": "^0.1.12",
    "cordova-plugin-apprate": "^1.7.2",
    "cordova-plugin-call-number": "^1.0.1",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-market": "^1.2.0",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova.plugins.diagnostic": "^6.1.1",
    "core-js": "^3.8.2",
    "date-fns": "^2.16.1",
    "date-fns-tz": "^1.1.6",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^9.9.3",
    "ion2-calendar": "^3.5.0",
    "ionic-selectable": "^4.9.0",
    "leaflet": "^1.7.1",
    "leaflet-control-geocoder": "^1.13.0",
    "leaflet.gridlayer.googlemutant": "^0.10.2",
    "moment": "^2.29.1",
    "ngx-build-plus": "^14.0.0",
    "rxjs": "^6.6.3",
    "string-similarity": "^4.0.4",
    "sweetalert2": "^10.15.5",
    "tslib": "^2.0.0",
    "typescript": "4.6.4",
    "zone.js": "~0.11.4"

**Comment by robingenz** [comment] 2022-08-21 09:21
Maybe your XCode project is messed up: Please remove all temporary XCode files (just delete the whole ios folder and revert the changes via git) and run `npx cap open ios` again.

If this does not help i need a minimal, reproducible example so i can debug the issue.

**Comment by chrisvor** [comment] 2022-08-21 10:07
I did that already and recreated the ios project (which is something I didnt want to do as I need to re-do all the icon/graphics/splashscreens again), but the project wouldn't build again, same error.
I have a feeling it's related to the fact that I use @angular/fire as well because I need to call firebase callable functions too.  Before trying this plugin I used to use the capacitor-community plugins, but as I upgraded to Ionic 6 & Capacitor 4 they seem to not be compatible and switched to this plugin.
The app is currently in the app stores (Apple & Google) but it's using Ionic 5 and Capacitor 2. 
I dont understand what you mean by "minimal example"... this is not related to something functioning wrongly. It doesn't even build....

**Comment by robingenz** [comment] 2022-08-21 10:28
> which is something I didnt want to do as I need to re-do all the icon/graphics/splashscreens again

You shouldn't have to, as these files should be in git (as configured by default in a Capacitor app).

> I have a feeling it's related to the fact that I use @angular/fire as well because I need to call firebase callable functions too. 

`@angular/fire` should not be the problem because it's not related to the native platform.

> I dont understand what you mean by "minimal example"... this is not related to something functioning wrongly. It doesn't even build....

I currently have no demo app project with which I can reproduce the problem. So I can't help you at the moment. I need to be able to reproduce the problem locally to be able to debug it.
See [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) for more info.

**Comment by chrisvor** [comment] 2022-08-21 14:13
I created a brand new app, added the ios platform and ran npx cap sync and then npx cap open ios. And the app built find.
I then replaced the generated package.json with the one in my original project. Did npm install to install all the plugins and re-ran npx cap sync and npx cap open ios. The build fails with the error I get in the original project. 
I suppose this would help you debug this?

[Uploading minimal.zip…]()

**Comment by robingenz** [comment] 2022-08-21 14:58
Thank you. Please publish the project on GitHub as a reporsitory and post the link here.

**Comment by chrisvor** [comment] 2022-08-21 15:14
Here it is:

https://github.com/chrisvor/minimal.git

Thanks

**Comment by robingenz** [comment] 2022-08-21 20:26
You missed [this step](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/analytics#ios):

> Add the `CapacitorFirebaseAnalytics/Analytics` pod to your `Podfile` (usually `ios/App/Podfile`):

```diff
target 'App' do
capacitor_pods
# Add your Pods here
+  pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'
end
```

Please make sure you have followed the installation instructions carefully and try again.

Let me know if the error still occurs.

**Comment by chrisvor** [comment] 2022-08-22 05:03
I did update the podfile in my full project, I forgot it on the minimal example. I updated it there too now (github updated) but the issue still exists (as in my full project)

**Comment by chrisvor** [comment] 2022-08-23 12:08
Any suggestions as to what is the problem and how to fix?

**Comment by robingenz** [comment] 2022-08-23 21:06
I will look at it this week.

**Comment by chrisvor** [comment] 2022-08-28 13:57
Hi :) Did you get a chance to have a look at this? 
Many thanks!

**Comment by robingenz** [comment] 2022-08-29 10:10
I could reproduce your issue. Something was wrong with your `project.pbxproj` file. After removing and adding the ios platform I had the following content:

<details>
<summary>Details</summary>

```
// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 48;
	objects = {

/* Begin PBXBuildFile section */
		2FAD9763203C412B000D30F8 /* config.xml in Resources */ = {isa = PBXBuildFile; fileRef = 2FAD9762203C412B000D30F8 /* config.xml */; };
		50379B232058CBB4000EE86E /* capacitor.config.json in Resources */ = {isa = PBXBuildFile; fileRef = 50379B222058CBB4000EE86E /* capacitor.config.json */; };
		504EC3081FED79650016851F /* AppDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = 504EC3071FED79650016851F /* AppDelegate.swift */; };
		504EC30D1FED79650016851F /* Main.storyboard in Resources */ = {isa = PBXBuildFile; fileRef = 504EC30B1FED79650016851F /* Main.storyboard */; };
		504EC30F1FED79650016851F /* Assets.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = 504EC30E1FED79650016851F /* Assets.xcassets */; };
		504EC3121FED79650016851F /* LaunchScreen.storyboard in Resources */ = {isa = PBXBuildFile; fileRef = 504EC3101FED79650016851F /* LaunchScreen.storyboard */; };
		50B271D11FEDC1A000F3C39B /* public in Resources */ = {isa = PBXBuildFile; fileRef = 50B271D01FEDC1A000F3C39B /* public */; };
		A084ECDBA7D38E1E42DFC39D /* Pods_App.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = AF277DCFFFF123FFC6DF26C7 /* Pods_App.framework */; };
/* End PBXBuildFile section */

/* Begin PBXFileReference section */
		2FAD9762203C412B000D30F8 /* config.xml */ = {isa = PBXFileReference; lastKnownFileType = text.xml; path = config.xml; sourceTree = "<group>"; };
		50379B222058CBB4000EE86E /* capacitor.config.json */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.json; path = capacitor.config.json; sourceTree = "<group>"; };
		504EC3041FED79650016851F /* App.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = App.app; sourceTree = BUILT_PRODUCTS_DIR; };
		504EC3071FED79650016851F /* AppDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppDelegate.swift; sourceTree = "<group>"; };
		504EC30C1FED79650016851F /* Base */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Base; path = Base.lproj/Main.storyboard; sourceTree = "<group>"; };
		504EC30E1FED79650016851F /* Assets.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = Assets.xcassets; sourceTree = "<group>"; };
		504EC3111FED79650016851F /* Base */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Base; path = Base.lproj/LaunchScreen.storyboard; sourceTree = "<group>"; };
		504EC3131FED79650016851F /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
		50B271D01FEDC1A000F3C39B /* public */ = {isa = PBXFileReference; lastKnownFileType = folder; path = public; sourceTree = "<group>"; };
		AF277DCFFFF123FFC6DF26C7 /* Pods_App.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = Pods_App.framework; sourceTree = BUILT_PRODUCTS_DIR; };
		AF51FD2D460BCFE21FA515B2 /* Pods-App.release.xcconfig */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = text.xcconfig; name = "Pods-App.release.xcconfig"; path = "Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig"; sourceTree = "<group>"; };
		FC68EB0AF532CFC21C3344DD /* Pods-App.debug.xcconfig */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = text.xcconfig; name = "Pods-App.debug.xcconfig"; path = "Pods/Target Support Files/Pods-App/Pods-App.debug.xcconfig"; sourceTree = "<group>"; };
/* End PBXFileReference section */

/* Begin PBXFrameworksBuildPhase section */
		504EC3011FED79650016851F /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
				A084ECDBA7D38E1E42DFC39D /* Pods_App.framework in Frameworks */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
		27E2DDA53C4D2A4D1A88CE4A /* Frameworks */ = {
			isa = PBXGroup;
			children = (
				AF277DCFFFF123FFC6DF26C7 /* Pods_App.framework */,
			);
			name = Frameworks;
			sourceTree = "<group>";
		};
		504EC2FB1FED79650016851F = {
			isa = PBXGroup;
			children = (
				504EC3061FED79650016851F /* App */,
				504EC3051FED79650016851F /* Products */,
				7F8756D8B27F46E3366F6CEA /* Pods */,
				27E2DDA53C4D2A4D1A88CE4A /* Frameworks */,
			);
			sourceTree = "<group>";
		};
		504EC3051FED79650016851F /* Products */ = {
			isa = PBXGroup;
			children = (
				504EC3041FED79650016851F /* App.app */,
			);
			name = Products;
			sourceTree = "<group>";
		};
		504EC3061FED79650016851F /* App */ = {
			isa = PBXGroup;
			children = (
				50379B222058CBB4000EE86E /* capacitor.config.json */,
				504EC3071FED79650016851F /* AppDelegate.swift */,
				504EC30B1FED79650016851F /* Main.storyboard */,
				504EC30E1FED79650016851F /* Assets.xcassets */,
				504EC3101FED79650016851F /* LaunchScreen.storyboard */,
				504EC3131FED79650016851F /* Info.plist */,
				2FAD9762203C412B000D30F8 /* config.xml */,
				50B271D01FEDC1A000F3C39B /* public */,
			);
			path = App;
			sourceTree = "<group>";
		};
		7F8756D8B27F46E3366F6CEA /* Pods */ = {
			isa = PBXGroup;
			children = (
				FC68EB0AF532CFC21C3344DD /* Pods-App.debug.xcconfig */,
				AF51FD2D460BCFE21FA515B2 /* Pods-App.release.xcconfig */,
			);
			name = Pods;
			sourceTree = "<group>";
		};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
		504EC3031FED79650016851F /* App */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = 504EC3161FED79650016851F /* Build configuration list for PBXNativeTarget "App" */;
			buildPhases = (
				6634F4EFEBD30273BCE97C65 /* [CP] Check Pods Manifest.lock */,
				504EC3001FED79650016851F /* Sources */,
				504EC3011FED79650016851F /* Frameworks */,
				504EC3021FED79650016851F /* Resources */,
				9592DBEFFC6D2A0C8D5DEB22 /* [CP] Embed Pods Frameworks */,
				5E068B63AA667C57AF1D8175 /* [CP] Copy Pods Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = App;
			productName = App;
			productReference = 504EC3041FED79650016851F /* App.app */;
			productType = "com.apple.product-type.application";
		};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
		504EC2FC1FED79650016851F /* Project object */ = {
			isa = PBXProject;
			attributes = {
				LastSwiftUpdateCheck = 0920;
				LastUpgradeCheck = 0920;
				TargetAttributes = {
					504EC3031FED79650016851F = {
						CreatedOnToolsVersion = 9.2;
						LastSwiftMigration = 1100;
						ProvisioningStyle = Automatic;
					};
				};
			};
			buildConfigurationList = 504EC2FF1FED79650016851F /* Build configuration list for PBXProject "App" */;
			compatibilityVersion = "Xcode 8.0";
			developmentRegion = en;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = 504EC2FB1FED79650016851F;
			productRefGroup = 504EC3051FED79650016851F /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				504EC3031FED79650016851F /* App */,
			);
		};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
		504EC3021FED79650016851F /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				504EC3121FED79650016851F /* LaunchScreen.storyboard in Resources */,
				50B271D11FEDC1A000F3C39B /* public in Resources */,
				504EC30F1FED79650016851F /* Assets.xcassets in Resources */,
				50379B232058CBB4000EE86E /* capacitor.config.json in Resources */,
				504EC30D1FED79650016851F /* Main.storyboard in Resources */,
				2FAD9763203C412B000D30F8 /* config.xml in Resources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

/* Begin PBXShellScriptBuildPhase section */
		5E068B63AA667C57AF1D8175 /* [CP] Copy Pods Resources */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
			);
			name = "[CP] Copy Pods Resources";
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "\"${PODS_ROOT}/Target Support Files/Pods-App/Pods-App-resources.sh\"\n";
			showEnvVarsInLog = 0;
		};
		6634F4EFEBD30273BCE97C65 /* [CP] Check Pods Manifest.lock */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
				"${PODS_PODFILE_DIR_PATH}/Podfile.lock",
				"${PODS_ROOT}/Manifest.lock",
			);
			name = "[CP] Check Pods Manifest.lock";
			outputPaths = (
				"$(DERIVED_FILE_DIR)/Pods-App-checkManifestLockResult.txt",
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "diff \"${PODS_PODFILE_DIR_PATH}/Podfile.lock\" \"${PODS_ROOT}/Manifest.lock\" > /dev/null\nif [ $? != 0 ] ; then\n    # print error to STDERR\n    echo \"error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.\" >&2\n    exit 1\nfi\n# This output is used by Xcode 'outputs' to avoid re-running this script phase.\necho \"SUCCESS\" > \"${SCRIPT_OUTPUT_FILE_0}\"\n";
			showEnvVarsInLog = 0;
		};
		9592DBEFFC6D2A0C8D5DEB22 /* [CP] Embed Pods Frameworks */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
			);
			name = "[CP] Embed Pods Frameworks";
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "\"${PODS_ROOT}/Target Support Files/Pods-App/Pods-App-frameworks.sh\"\n";
			showEnvVarsInLog = 0;
		};
/* End PBXShellScriptBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
		504EC3001FED79650016851F /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				504EC3081FED79650016851F /* AppDelegate.swift in Sources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXSourcesBuildPhase section */

/* Begin PBXVariantGroup section */
		504EC30B1FED79650016851F /* Main.storyboard */ = {
			isa = PBXVariantGroup;
			children = (
				504EC30C1FED79650016851F /* Base */,
			);
			name = Main.storyboard;
			sourceTree = "<group>";
		};
		504EC3101FED79650016851F /* LaunchScreen.storyboard */ = {
			isa = PBXVariantGroup;
			children = (
				504EC3111FED79650016851F /* Base */,
			);
			name = LaunchScreen.storyboard;
			sourceTree = "<group>";
		};
/* End PBXVariantGroup section */

/* Begin XCBuildConfiguration section */
		504EC3141FED79650016851F /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ANALYZER_NONNULL = YES;
				CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
				CLANG_CXX_LANGUAGE_STANDARD = "gnu++14";
				CLANG_CXX_LIBRARY = "libc++";
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
				CLANG_WARN_BOOL_CONVERSION = YES;
				CLANG_WARN_COMMA = YES;
				CLANG_WARN_CONSTANT_CONVERSION = YES;
				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
				CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
				CLANG_WARN_EMPTY_BODY = YES;
				CLANG_WARN_ENUM_CONVERSION = YES;
				CLANG_WARN_INFINITE_RECURSION = YES;
				CLANG_WARN_INT_CONVERSION = YES;
				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
				CLANG_WARN_STRICT_PROTOTYPES = YES;
				CLANG_WARN_SUSPICIOUS_MOVE = YES;
				CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
				CLANG_WARN_UNREACHABLE_CODE = YES;
				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
				CODE_SIGN_IDENTITY = "iPhone Developer";
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = dwarf;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				ENABLE_TESTABILITY = YES;
				GCC_C_LANGUAGE_STANDARD = gnu11;
				GCC_DYNAMIC_NO_PIC = NO;
				GCC_NO_COMMON_BLOCKS = YES;
				GCC_OPTIMIZATION_LEVEL = 0;
				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
				);
				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
				GCC_WARN_UNDECLARED_SELECTOR = YES;
				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
				GCC_WARN_UNUSED_FUNCTION = YES;
				GCC_WARN_UNUSED_VARIABLE = YES;
				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
				MTL_ENABLE_DEBUG_INFO = YES;
				ONLY_ACTIVE_ARCH = YES;
				SDKROOT = iphoneos;
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;
				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
			};
			name = Debug;
		};
		504EC3151FED79650016851F /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ANALYZER_NONNULL = YES;
				CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
				CLANG_CXX_LANGUAGE_STANDARD = "gnu++14";
				CLANG_CXX_LIBRARY = "libc++";
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
				CLANG_WARN_BOOL_CONVERSION = YES;
				CLANG_WARN_COMMA = YES;
				CLANG_WARN_CONSTANT_CONVERSION = YES;
				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
				CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
				CLANG_WARN_EMPTY_BODY = YES;
				CLANG_WARN_ENUM_CONVERSION = YES;
				CLANG_WARN_INFINITE_RECURSION = YES;
				CLANG_WARN_INT_CONVERSION = YES;
				CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
				CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
				CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
				CLANG_WARN_STRICT_PROTOTYPES = YES;
				CLANG_WARN_SUSPICIOUS_MOVE = YES;
				CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
				CLANG_WARN_UNREACHABLE_CODE = YES;
				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
				CODE_SIGN_IDENTITY = "iPhone Developer";
				COPY_PHASE_STRIP = NO;
				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
				ENABLE_NS_ASSERTIONS = NO;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				GCC_C_LANGUAGE_STANDARD = gnu11;
				GCC_NO_COMMON_BLOCKS = YES;
				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
				GCC_WARN_UNDECLARED_SELECTOR = YES;
				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
				GCC_WARN_UNUSED_FUNCTION = YES;
				GCC_WARN_UNUSED_VARIABLE = YES;
				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
				MTL_ENABLE_DEBUG_INFO = NO;
				SDKROOT = iphoneos;
				SWIFT_OPTIMIZATION_LEVEL = "-Owholemodule";
				VALIDATE_PRODUCT = YES;
			};
			name = Release;
		};
		504EC3171FED79650016851F /* Debug */ = {
			isa = XCBuildConfiguration;
			baseConfigurationReference = FC68EB0AF532CFC21C3344DD /* Pods-App.debug.xcconfig */;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				CODE_SIGN_STYLE = Automatic;
				CURRENT_PROJECT_VERSION = 1;
				INFOPLIST_FILE = App/Info.plist;
				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				MARKETING_VERSION = 1.0;
				OTHER_SWIFT_FLAGS = "$(inherited) \"-D\" \"COCOAPODS\" \"-DDEBUG\"";
				PRODUCT_BUNDLE_IDENTIFIER = com.example.app;
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Debug;
		};
		504EC3181FED79650016851F /* Release */ = {
			isa = XCBuildConfiguration;
			baseConfigurationReference = AF51FD2D460BCFE21FA515B2 /* Pods-App.release.xcconfig */;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				CODE_SIGN_STYLE = Automatic;
				CURRENT_PROJECT_VERSION = 1;
				INFOPLIST_FILE = App/Info.plist;
				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				MARKETING_VERSION = 1.0;
				PRODUCT_BUNDLE_IDENTIFIER = com.example.app;
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_ACTIVE_COMPILATION_CONDITIONS = "";
				SWIFT_VERSION = 5.0;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Release;
		};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
		504EC2FF1FED79650016851F /* Build configuration list for PBXProject "App" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				504EC3141FED79650016851F /* Debug */,
				504EC3151FED79650016851F /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
		504EC3161FED79650016851F /* Build configuration list for PBXNativeTarget "App" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				504EC3171FED79650016851F /* Debug */,
				504EC3181FED79650016851F /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
/* End XCConfigurationList section */
	};
	rootObject = 504EC2FC1FED79650016851F /* Project object */;
}
```
</details>

This way it worked for me.

**Comment by chrisvor** [comment] 2022-08-29 11:23
In other words to fix it I should remove the iOS folder and rerun npx cap add ios?

In this "minimal" project, it's a brand new project and the platforms were added when I created the minimal project for this submission.... I fear removing and recreating won't solve it for me. It's probably something "deeper", i.e. the way npx is creating the platform maybe? Any configuration for npx that affects how the platforms are created?

**Comment by robingenz** [comment] 2022-08-29 11:28
> In other words to fix it I should remove the iOS folder and rerun npx cap add ios?

Yes

> In this "minimal" project, it's a brand new project and the platforms were added when I created the minimal project for this submission.... I fear removing and recreating won't solve it for me. It's probably something "deeper", i.e. the way npx is creating the platform maybe? Any configuration for npx that affects how the platforms are created?

Maybe. But this is hard for me to debug. Do you use the latest XCode version?

**Comment by chrisvor** [comment] 2022-08-29 11:59
yes, there are no other pending updates
anything you can guide me to check on my side?

**Comment by chrisvor** [comment] 2022-08-29 16:20
@robingenz  are you sure the project you tested has firebaseAnalytics added? the project.pbxproj you gave me above does not have any reference to FirebaseAnalytics, whereas my version of the same file has:
/* Begin PBXBuildFile section */
(......)
838C9DB928B4F1EA00E30F4A /* FirebaseAnalytics in Frameworks */ = {isa = PBXBuildFile; productRef = 838C9DB828B4F1EA00E30F4A /* FirebaseAnalytics */; };
(.......)
/* End PBXBuildFile section */

Could you commit your changes to my github?

**Comment by robingenz** [comment] 2022-08-29 17:04
> are you sure the project you tested has firebaseAnalytics added?

Yes, look at the official demo app for example: https://github.com/robingenz/capacitor-firebase-plugin-demo/blob/main/ios/App/App.xcodeproj/project.pbxproj
This reference is not needed.
Just try the demo app.

**Comment by Aidenjl193** [comment] 2022-09-01 11:10
We're experiencing the same issue and rebuilding the iOS folder hasn't fixed it for us.

**Comment by robingenz** [comment] 2022-09-01 11:48
Hi @Aidenjl193,
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by robingenz** [comment] 2022-09-01 17:55
@Aidenjl193 You missed one setup step. Please have a look at this comment: https://github.com/capawesome-team/capacitor-firebase/issues/182#issuecomment-1221615111

**Comment by chrisvor** [comment] 2022-09-01 20:50
I forgot to update this with my findings:  I removed iOS folder and re-added the platform but the issue was NOT fixed. And then I tried removing the capacitor-firebase/authentication plugin, and then re-added it (without rebuilding between the two). The issue was fixed then. I dont know the reason....

**Comment by Aidenjl193** [comment] 2022-09-02 08:22
> @Aidenjl193 You missed one setup step. Please have a look at this comment: [#182 (comment)](https://github.com/capawesome-team/capacitor-firebase/issues/182#issuecomment-1221615111)

I have "pod 'CapacitorFirebaseAnalytics', :path => '../../node_modules/@capacitor-firebase/analytics'" in there, changing the CapacitorFirebaseAnalytics to CapacitorFirebaseAnalytics/Analytics just gets reverted to CapacitorFirebaseAnalytics upon building.

Am I missing something here?

**Comment by Aidenjl193** [comment] 2022-09-02 08:32
> @Aidenjl193 You missed one setup step. Please have a look at this comment: [#182 (comment)](https://github.com/capawesome-team/capacitor-firebase/issues/182#issuecomment-1221615111)

Yeah, I was being a silly goose. Turns out I was looking at the def capacitor_pods block above instead of the app block below. Thanks for the help

**Comment by robingenz** [comment] 2022-09-02 08:54
Great, in that case both of you no longer have the problem and I can close the issue.

**Closed by robingenz** 2022-09-02 08:54 UTC
Labels: needs: reproduction, needs: triage, package: analytics
