### ISSUE TITLE
bug: firebase collections not returning timestamps on ios

### ISSUE THREAD

**Issue by Tsquared86** [capawesome-team/capacitor-firebase#533] opened 2024-01-04 15:59 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.2.0

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

capacitor does not return values for a firebase timestamp.  when I loop over the collection results it just shows as undefined. I tried using the regular firebase sdk in the web and it returns the same data as it should with all values. 

### Expected behavior

It should return a firebase time stamp value. 

### Reproduction

GitHub.com/tsquared86

### Steps to reproduce

nvm 16, get a collection with a document that has a time stamp value

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/ios: 5.0.4

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-01-04 18:39
I close this as duplicate of #474.

**Closed by robingenz** 2024-01-04 18:39 UTC
Labels: bug/fix, needs: triage
