### ISSUE TITLE
feat: createChannel and deleteChannel Android

### ISSUE THREAD

**Issue by josuelmm** [capawesome-team/capacitor-firebase#217] opened 2022-10-05 13:48 UTC
Currently the PushNotifications plugin @capacitor/push-notifications
Allows you to create channels and delete them, this only applies to Android, it would be nice to add it.

**Comment by robingenz** [comment] 2022-10-05 14:16
Yes, definitely.
 
I close this issue as duplicate of #94.

**Closed by robingenz** 2022-10-05 14:16 UTC
Labels: needs: triage
