### ISSUE TITLE
bug(messaging): `notificationReceived` fires only for the last message received while the app is killed

### ISSUE THREAD

**Issue by crowbait** [capawesome-team/capacitor-firebase#210] opened 2022-09-30 23:48 UTC
**Plugin(s):**

"@capacitor-firebase/messaging": "^1.1.0"

**Platform(s):**

Android

**Current behavior:**

If a data-only notification is received while the app is killed or the device is in doze, the `notficationRecieved` listener event does not fire. When the app is opened the next time, the listener fires only for the last message recieved while the app was killed. Every other message is dropped.

**Expected behavior:**

Code given to the listener should be executed regardless of doze or killed app. Documentation states _If the app is in the background, then this listener is only called on data push notifications._, but does not make any statement about the app being killed.

**Steps to reproduce:**

Add listener and send data-only notification to device while app is killed:
```
    FirebaseMessaging.addListener('notificationReceived', event => {
      console.log("Notification recieved: ", event);    //fires if message is recieved while app in foreground or background
      if(event.notification.data?.payload){                  //but not if app is killed
        //do something traceable which doesn't need console
        //for example, write a small file with messageid as filename
      }
    });
```
message:
```
        token: "notificationtoken",
        data: {
          payload: "messagePayload"
        },
        android: {
          priority: "high"
        }
```

**Capacitor doctor:**

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.2.0
  @capacitor/ios: 4.2.0
  @capacitor/android: 4.2.0

[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2022-10-01 06:22
Thank you for your request. I will have a look. Should be a bug.

**Comment by robingenz** [comment] 2022-10-01 09:42
I looked at it and was able to reproduce the problem. The problem also exists on iOS. However, I cannot currently fix the bug on iOS because Capacitor does not allow it. I have created a feature request. (see https://github.com/ionic-team/capacitor/issues/5967)
As soon as Capacitor supports it, I will fix it on Android and iOS.

**Comment by Traxx2012** [comment] 2022-10-01 10:37
From the issue you opened, I read that immediate handling of data-only notifications (eg displaying a local notification in response) isn't even the intended behavior? So the fact that (although just one) notifications are handled only when the app launches the next time is intended?

**Comment by robingenz** [comment] 2022-10-01 12:16
It is the intended behavior, but only if the application is running in the background (so only if the application was not force closed).

**Comment by Traxx2012** [comment] 2022-10-01 17:27
Is there any way of achieving exactly that? Handling notifications while the app has been killed?

**Comment by robingenz** [comment] 2022-10-01 18:06
Yes, with native code (e.g. Capacitor Plugin). 
What is your specific use case?

**Comment by Traxx2012** [comment] 2022-10-01 18:16
Chat feature in the app should display notifications as soon as they come (minus delay and restrictions, but before the user manually opens the app). As user could still just dismiss the notification, I need to perform operations on it before the user can dismiss it - so normal message notifications are unfeasible and data notifications don't work from within JS. So guess that means I have to learn Java after all.
I just hope I can kind of follow a guide on how to implement FCM handling on Android without the native capacitor plugin breaking everything (I still need some functionality from JS to handle notifications when the app is open after all).

**Comment by robingenz** [comment] 2022-10-01 18:26
You could send two notifications (one Notification message and one Data message) at the same time. This is how a client of mine does it with a similar problem.
Maybe this would also be a solution for you.

**Comment by Traxx2012** [comment] 2022-10-01 18:43
That is a nice idea. However, it would mean double the calls to firebase cloud functions (if I had a server that could handle a call on every message, I'd just save them to the DB and fetch them on login)... So yes, I think I will have to investigate the Java side of things in the coming days.

**Comment by Traxx2012** [comment] 2022-10-02 01:00
Just for the sake of being thorough: I just tested the behavior in a production (non-debug) app via internal testing track on google play.
- messages before the most recent one still get dropped when the app opens
- data-messages don't get handled if the app has been swiped ("closed") from recent apps tray; should be passed to listener on next app launch then

I did this test because I learned that push notifications allegedly have different behavior in debug vs production and also Android is said to kill services associated with an app on close if the app is debug.

**Comment by Traxx2012** [comment] 2022-10-02 19:28
This might be a bit off-topic, but for anyone passing here on the hunt for a solution to my problem, adding your own FirebaseMessagingService extender doesn't play well with capacitor either. I've written about that here: https://github.com/ionic-team/capacitor-plugins/issues/1211

**Comment by robingenz** [comment] 2023-04-21 16:06
This should be fixed in Capacitor 5 (see https://github.com/ionic-team/capacitor/issues/5967 and #355).

**Closed by robingenz** 2023-04-21 16:06 UTC
Labels: platform: android, bug/fix, platform: ios, package: messaging
