### ISSUE TITLE
bug: iOS analytics crash: Cannot get flag for unregistered flag

### ISSUE THREAD

**Issue by vadimwe** [capawesome-team/capacitor-firebase#343] opened 2023-03-23 16:24 UTC
**Plugin(s):**

analytics

**Platform(s):**

iOS

**Current behavior:**

Errors on iOS app start:
10.2.0 - [FirebaseAnalytics][I-ACS800014] Cannot get flag for unregistered flag. SDK name, flag name: app_measurement, session_stitching_token_feature_enabled

**Expected behavior:**

Start with no errors

**Steps to reproduce:**

Install package in strict with instructions

**Related code:**

```
insert short code snippets here
```

**Other information:**

<img width="1512" alt="Снимок экрана 2023-03-23 в 18 22 42" src="https://user-images.githubusercontent.com/2635452/227269326-afd09fba-de8d-4825-80f4-a4ac771bfd32.png">

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

Installed Dependencies:

  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1
  @capacitor/ios: 4.7.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2023-03-23 16:53
This is not an error, but only a warning from the Firebase iOS SDK. You can ignore it (see [this comment](https://github.com/firebase/firebase-ios-sdk/issues/10940#issuecomment-1470327126)). The app does not crash because of this. The crash must have another reason. Please check your logs again. 

Since this is not a bug in the plugin, I am closing this issue.

**Closed by robingenz** 2023-03-23 16:53 UTC
Labels: needs: triage, platform: ios, package: analytics
