### ISSUE TITLE
No such module 'FirebaseCore'

### ISSUE THREAD

**Issue by 24jr** [capawesome-team/capacitor-firebase#242] opened 2022-11-08 16:42 UTC
/node_modules/@capacitor-firebase/analytics/ios/Plugin/FirebaseAnalytics.swift:4:8: No such module 'FirebaseCore'

I previously had set up with https://github.com/capacitor-community/firebase-analytics/pull/123 which no longer works for capacitor v4 so switching to this if works

this is podfile I have do i need to do something else? When I play the app in xCode I get the above error
```
# require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAnalytics', :path => '../../../../node_modules/@capacitor-firebase/analytics'
  pod 'CapacitorDevice', :path => '../../../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorLocalNotifications', :path => '../../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/@capacitor/share'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

# post_install do |installer|
#   assertDeploymentTarget(installer)
# end

```

**Comment by robingenz** [comment] 2022-11-08 17:27
I close this issue as duplicate of #182

**Closed** 2022-11-08 17:28 UTC
Labels: duplicate, needs: triage, package: analytics
