### ISSUE TITLE
bug: Add support for Capacitor 4

### ISSUE THREAD

**Issue by RRGT19** [capawesome-team/capacitor-firebase#166] opened 2022-07-30 22:42 UTC
**Plugin(s):**
All

**Current behavior:**
When upgrading from Capacitor 3 to Capacitor 4, `npm install` fails because of peer dependencies pointing to Capacitor 3.

**Expected behavior:**
Install should not return any dependency error.

**Other information:**
Capacitor 4 has been released recently, see releases [here](https://github.com/ionic-team/capacitor/releases). The `peerDependencies` of all your plugins need an update.

**Comment by robingenz** [comment] 2022-07-31 07:36
Closed as duplicate of #125

**Closed by robingenz** 2022-07-31 07:36 UTC
Labels: needs: triage
