### ISSUE TITLE
Troubleshooting Date-Time Query Issues

### ISSUE THREAD

**Issue by SureshKumarToverto** [capawesome-team/capacitor-firebase#590] opened 2024-03-20 16:09 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

Latest

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

Got empty array 
- userList  = []

### Expected behavior

We array of value

```
 userList = [{"LoggedinAt":"Timestamp(seconds=1675166136, nanoseconds=561000000)","DisplayName":"Test","CreatedOn":"Timestamp(seconds=1701674105, nanoseconds=723000000)"}]
```

### Reproduction

https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/firestore

### Steps to reproduce

```ts
public GetAllCheckInUser(filterData): any {
    var date =  moment(new Date()).subtract(1, 'h').toDate();
    console.log('date',date);    
    return from(FirebaseFirestore.getCollection({
      reference: 'LoggedinUser',
      compositeFilter: {
        type: 'and',
        queryConstraints: [         
          {
            type: 'where',
            fieldPath: 'LoggedinAt',
            opStr: '>',
            value: date,
          },
        ],
      },
    }))
      .pipe(
        map((actions) => actions.snapshots.map(a => {    
          const data = a.data as any;
          const id = a.id;
          return { id, ...data };
        })),
        map((data: any) => {
          return _.filter(data, (item) => item.AccountNumber !== null);
        })
      );
  }
 ```

### Other information

 FYI :  In Firebase we have value like 
  
![image](https://github.com/capawesome-team/capacitor-firebase/assets/155732803/6150d6e6-9db8-4c0e-a796-8e34517fcf25)

### Capacitor doctor

ionic cap build android --prod

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-03-20 16:43
Which plugin version do you use?

**Comment by robingenz** [comment] 2024-03-20 16:44
I close this issue as duplicate of #474.

**Closed by robingenz** 2024-03-20 16:44 UTC
Labels: platform: android, bug/fix, needs: triage, platform: ios, package: firestore
