### ISSUE TITLE
feat: Missing GDPR Compliance Guide

### ISSUE THREAD

**Issue by AmitMY** [capawesome-team/capacitor-firebase#589] opened 2024-03-17 07:54 UTC
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

The [analytics](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/analytics) package has the following code which runs in the app:
```ts
await FirebaseAnalytics.setEnabled({enabled: false});
```
When integrating firebase analytics, users must grant explicit informed consent, so this needs to be the default behavior, to disallow sending anything.

### Preferred solution

Developer must set up this in the beginning of the execution:
```ts
await FirebaseAnalytics.setEnabled({enabled: false});
```
(unless it could be that on iOS/Android you send crash events regardless, in that case, there should be an environment flag that starts it as false)

- Every time the developer logs an event, when analytics is not enabled, it should be added to an event queue.
- If at any point `FirebaseAnalytics` becomes enabled (let's say, user clicked "accept") all events should be sent to the server, ideally with their original timing

### Alternative options

Developers can implement such a behavior by wrapping around `FirebaseAnalytics` with their own service, but, it is not trivial to handle `startTrace` and `stopTrace` for example.

### Additional context

https://secureprivacy.ai/blog/google-analytics-4-gdpr-compliance

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment] 2024-03-17 08:19
I think you are looking for the `setConsent` method. So this issue should be a duplicate of #518.

**Comment by robingenz** [comment] 2024-03-18 08:54
I think so. I am closing this issue as a duplicate of #518 . If it turns out that you were looking for something else, we can reopen this issue.

**Closed by robingenz** 2024-03-18 08:54 UTC
Labels: feature, needs: triage, package: analytics
