### ISSUE TITLE
bug: capacitor-firebase/authentication dependency update needed

### ISSUE THREAD

**Issue by njvb** [capawesome-team/capacitor-firebase#762] opened 2024-11-25 13:01 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.2.0

### Platform(s)

- [X] Android
- [X] iOS
- [X] Web

### Current behavior

Firebase is now on version 11. Please update the dependency:

npm warn Could not resolve dependency:
npm warn peerOptional firebase@"^10.9.0" from @capacitor-firebase/authentication@6.2.0
npm warn node_modules/@capacitor-firebase/authentication
npm warn   @capacitor-firebase/authentication@"^6.0.0" from the root project

### Expected behavior

Update packages without dependency warning

### Reproduction

n/a

### Steps to reproduce

nom update (any outdated package in project)

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.2.0
  @capacitor/core: 6.2.0
  @capacitor/android: 6.2.0
  @capacitor/ios: 6.2.0

Installed Dependencies:

  @capacitor/cli: 6.1.2
  @capacitor/core: 6.1.2
  @capacitor/android: 6.1.2
  @capacitor/ios: 6.1.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-11-25 13:28
Closed as duplicate of #759.

**Closed by robingenz** 2024-11-25 13:28 UTC
Labels: bug/fix, needs: triage
