### ISSUE TITLE
bug: Issue with presentationOptions Config Affecting Background Notification Sound

### ISSUE THREAD

**Issue by sinanverve7** [capawesome-team/capacitor-firebase#601] opened 2024-03-28 09:11 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [X] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

5.4.1

### Platform(s)

- [ ] Android
- [X] iOS
- [ ] Web

### Current behavior

When configuring FirebaseMessaging's presentationOptions in my Capacitor app:

- Setting presentationOptions to an empty array ([]) suppresses sound for both foreground and background notifications, leading to silent background notifications, which is not desired.

`FirebaseMessaging: {
  presentationOptions: [],
},
`

- Conversely, including "sound" in presentationOptions (["sound"]) activates sound for both foreground and background notifications. This is problematic as it doesn't allow for silent handling of foreground notifications while ensuring background notifications are audible.

`Conversely, including "sound" in presentationOptions (["sound"]) activates sound for both foreground and background notifications. This is problematic as it doesn't allow for silent handling of foreground notifications while ensuring background notifications are audible.`

This configuration behavior does not allow for differentiated handling of notification sounds based on app state (foreground vs. background), limiting flexibility in notification management.

### Expected behavior

- For background notifications, I want them to be accompanied by a sound.
- For foreground notifications, I prefer to handle them manually (e.g., via local notifications or custom logic) without an automatic sound.

### Reproduction

https://github.com/sinanverve7/fcm-issue-reproduction

### Steps to reproduce

1.  i have wrote the configuration iam using in project in capacitor.config.js.
2. just run this project on iphone.
3. enable fcm on this app
4. keill the app
5. send the fcm message to the app.
6. check the notification sound on background mode

### Other information

i have integrated capacitor-firebase/authentication aswell ( 5.1.0 ) 

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.7.4
  @capacitor/core: 5.7.4
  @capacitor/android: 5.7.4
  @capacitor/ios: 5.7.4

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 4.8.1
  @capacitor/core: 4.8.1
  @capacitor/ios: 4.8.1

[success] iOS looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-03-28 09:49
I am closing this issue as this is the intended behavior and not a bug.

**Closed by robingenz** 2024-03-28 09:49 UTC
Labels: bug/fix, needs: triage, platform: ios, package: messaging

**Comment by sinanverve7** [comment] 2024-03-28 09:53
Hi @robingenz 
so if i didnot give "sound" as a parameter in presentationOptions like below, will it mute both foreground and background notification?
FirebaseMessaging: { presentationOptions: [], },

**Comment by sinanverve7** [comment] 2024-03-28 12:44
hi @robingenz  in my case it silences the background notification aswell.? it is opposite to the intended behaviour.

**Comment by robingenz** [comment] 2024-03-28 13:02
I misread your issue.

> so if i didnot give "sound" as a parameter in presentationOptions like below, will it mute both foreground and background notification?

No, this only affects the foreground. I have just tested it and had no problems. Make sure you set the `sound` property when sending the notification. Here is my nodejs code that I tested it with:

```ts
import { initializeApp, cert } from "firebase-admin/app";
import { Message, getMessaging } from "firebase-admin/messaging";

initializeApp({
  credential: cert("<PATH>"),
});

// This FCM token comes from the Capacitor Firebase Cloud Messaging plugin.
const token = "<TOKEN>";

const message: Message = {
  notification: {
    title: "Capacitor Firebase Messaging",
    body: "Hello world!",
  },
  apns: {
    payload: {
      aps: {
        sound: "default",
      },
    },
  },
  token: token,
};

// Send a message to the device corresponding to the provided FCM token
getMessaging()
  .send(message)
  .then((response) => {
    console.log("Successfully sent message: ", response);
  })
  .catch((error) => {
    console.log("Error sending message: ", error);
  });
```

For more information, take a look at this [Push Notification Guide for Capacitor](https://capawesome.io/blog/the-push-notifications-guide-for-capacitor/).

**Comment by sinanverve7** [comment] 2024-03-29 06:00
i have checked with above with our backend dev.we tried with both legacy firebase api and new api in both cases sound is muted.in the presentation option only "sound" parameter seems to have issue.the same notification gives sound with @capacitor/push-notifications.is there any other cases that blocks sound associated with push-notification ?


```
{
    "notification": {
      "body": "",
      "id": "value",
      "title": "check your card",
      "subtitle": "",
      "data": {
        "google.c.sender.id": "value",
        "aps": {
          "sound": "default",
          "alert": {
            "title": "check your card",
            "body": ""
          }
        },
        "gcm.notification.params": "value",
        "google.c.fid": "value",
        "google.c.a.e": "value",
        "gcm.message_id": "value"
      }
    }
  }
```

**Comment by robingenz** [comment] 2024-03-29 08:54
Have you tested it with the [official demo app](https://github.com/robingenz/capacitor-firebase-plugin-demo)?

**Comment by sinanverve7** [comment] 2024-03-29 08:58
No i havenot tested yet

**Comment by roosalyn** [comment] 2024-05-07 13:57
@robingenz I'm not sure if this is the right place to ask. But is it also intended that the `requestPermission()` will automatically return 'denied' when you have no presentationOptions configured? I would still like to show the permission prompt even when I don't show the notifications in the foreground.

**Comment by robingenz** [comment] 2024-05-07 14:05
@roosalyn Yes, this is intended. If no presentation options are defined, you do not need any permissions. If you have more questions, please create a discussion.
