### ISSUE TITLE
bug:  cannot find symbol variable AD_PERSONALIZATION

### ISSUE THREAD

**Issue by klaurtar** [capawesome-team/capacitor-firebase#683] opened 2024-07-27 02:12 UTC
### Plugin(s)

- [X] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Version

6.1.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When trying to run an Android app in Android studio that has capacitor-firebase/analytics@6.x.x and firebase@10.x.x installed through npm, the app fails with two errors stemming from FirebaseAnalyticsHelper.java file:
- cannot find symbol variable AD_PERSONALIZATION
- cannot find symbol variable AD_USER_DATA

<img width="1511" alt="Screenshot 2024-07-26 at 9 09 38 PM" src="https://github.com/user-attachments/assets/547a1e09-a9a7-4ab3-94c6-f3c349e08edb">

### Expected behavior

The app should succeed in building and running with the latest version of capacitor-firebase/analytics and firebase installed

### Reproduction

https://github.com/klaurtar/bad-capacitor-firebase/tree/main

### Steps to reproduce

Clone the repo, and npm install the dependencies. Once that is done, use the comman ```ionic cap sync android``` then ```ionic cap open android``` to open the project in Android Studio. Press the play button and the app should error out.

### Capacitor doctor

[warn] The bundledWebRuntime configuration option has been deprecated. Can be safely deleted.
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 6.1.1
  @capacitor/core: 6.1.1
  @capacitor/android: 6.1.1
  @capacitor/ios: 6.1.1

Installed Dependencies:

  @capacitor/core: 6.1.1
  @capacitor/cli: 6.1.1
  @capacitor/ios: 6.1.1
  @capacitor/android: 6.1.1

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-07-27 06:46
Please sync your Gradle project files and try it again. Let me know if this helps.

**Comment by klaurtar** [comment] 2024-07-27 15:34
@robingenz I have synced my Gradle project on both the reproduced error posted on Github and my real application and the same error persists. For now, the only way I have been able to get both applications to build and run is to revert back to @capacitor-firebase/analytics@5.4.1 using the force command which starts through peer dependency errors.

npm i @capacitor-firebase/analytics@5.4.1 --force

**Comment by robingenz** [comment] 2024-07-30 08:16
@klaurtar I took a look at your linked reproduction. Unfortunately, it is not a **minimal**, reproducible example. There are way too many dependencies. Please have a look at the [Capacitor Firebase Plugin Demo](https://github.com/robingenz/capacitor-firebase-plugin-demo) app. It uses `capacitor-firebase/analytics@6.x.x` and `firebase@10.x.x` and I could not reproduce your problem there.

**Comment by klaurtar** [comment] 2024-07-30 15:06
> @klaurtar I took a look at your linked reproduction. Unfortunately, it is not a **minimal**, reproducible example. There are way too many dependencies. Please have a look at the [Capacitor Firebase Plugin Demo](https://github.com/robingenz/capacitor-firebase-plugin-demo) app. It uses `capacitor-firebase/analytics@6.x.x` and `firebase@10.x.x` and I could not reproduce your problem there.

Ok, please do not close this topic. I will reproduce a minimal example with less dependencies and add it to the bug report.

**Comment by klaurtar** [comment] 2024-07-30 15:42
@robingenz Please check the provided repo again. I have npm uninstalled all npm packages aside from the the basic necessary requirements to scaffold an android app using the Ionic framework. I have kept `"@capacitor-firebase/analytics": "^6.1.0"`

This example has no bloat and is failing.

**Comment by robingenz** [comment] 2024-07-31 07:53
You specified a custom Firebase Analytics version instead of using the plugins default one. This fixes your issue:

![grafik](https://github.com/user-attachments/assets/65823be9-fc79-46e9-b1bb-5df60bd66e3b)

**Comment by klaurtar** [comment] 2024-07-31 13:50
Thanks for the quick reply. I believe I added this due to the instructions for the npm package. I don't need to specify it for it to work? Here is the part of the docs that caused confusion:

![Screenshot_2024-07-31-08-48-47-83_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/175eef3a-a92e-4f08-bd6d-45f6ab5b1880)

**Comment by robingenz** [comment] 2024-07-31 14:45
No, you don't need to specify it. The plugin will use the variable if a variable exists. Otherwise the default version is used. 

I will close this issue as completed.

**Closed by robingenz** 2024-07-31 14:45 UTC
Labels: platform: android, bug/fix, needs: triage, package: analytics
