### ISSUE TITLE
feat: Firebase Remote config alternative 

### ISSUE THREAD

**Issue by juanico18** [capawesome-team/capacitor-firebase#258] opened 2022-11-16 17:27 UTC
I am looking for an alternative to 
https://github.com/chemerisuk/cordova-plugin-firebase-config or
https://github.com/capacitor-community/firebase-remote-config that does not support capacitor 4.

Do you have in mind to work on it?

Thanks

**Comment by robingenz** [comment] 2022-11-16 18:41
I already work on it (see #240).
I close this issue as duplicate of #9.

**Closed by robingenz** 2022-11-16 18:41 UTC
Labels: duplicate

**Comment by robingenz** [comment] 2022-11-16 18:43
@juanico18 Would you be interested in testing the plugin as soon as it's ready?

**Comment by juanico18** [comment] 2022-11-17 08:49
Hi @robingenz Yes, I am interested. Although I am working on migrate from cordova to capacitor a project. So maybe it would take me some time to test.
My fault not review the issues looking for anyone else requiring the feature! I thought I did it
