### ISSUE TITLE
bug: Multiple unnecessary ngDoCheck runs

### ISSUE THREAD

**Issue by anthonyjuarezsolis** [capawesome-team/capacitor-firebase#390] opened 2023-06-24 05:56 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [ ] Android
- [ ] iOS
- [X] Web

### Current behavior

Bug report subject: Multiple unnecessary ngDoCheck runs in the Capacitor Firebase Authentication library

Angular: 16.1.1
ionic/angular: 7.0.14
capacitor-firebase/authentication: 5.0.0

Description of the problem:
I am using the Capacitor Firebase Authentication library in my Angular app with Capacitor. I have noticed that when using this library, the ngDoCheck method is executed multiple times unnecessarily, which is causing a negative impact on the performance of my application.

Additional details:
1. I have verified that the issue persists even in the Capacitor Firebase Authentication library demo project, which indicates that the behavior is related to the library's internal implementation.

2. The ngDoCheck method is executed repeatedly, even when no changes are made to the authentication-related application state or data.

3. I have made comparisons with other authentication libraries with Firebase (angular/fire) and I have found that they do not have this problem of unnecessary executions of ngDoCheck. This indicates that the issue is specifically related to the Capacitor Firebase Authentication library.

4. I have tried to comment out or remove parts of my code to isolate the problem and have confirmed that the unnecessary execution of ngDoCheck is directly related to the integration and use of the Capacitor Firebase Authentication library.

5. The issue negatively affects the performance of my application, as the ngDoCheck method is executed repeatedly, consuming resources and slowing down the overall response of the application.

Steps to reproduce the issue:
Clone the official Capacitor Firebase Authentication library demo project from the GitHub repository: https://github.com/robingenz/capacitor-firebase-authentication-demo

Open the login.page.ts file inside the login page folder (src/app/pages/login) in the cloned project.
Add the ngDoCheck method in the LoginPage class as follows:

1. Create a new Angular project with Capacitor.
2. Install and configure the Capacitor Firebase Authentication library according to the official documentation.
3. Implement authentication in the application using the methods and events provided by the library.
4. Observe the behavior of the ngDoCheck method and note unnecessary and repetitive executions.

```typescript
import { Component, DoCheck } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: 'login.page.html',
  styleUrls: ['login.page.scss'],
})
export class LoginPage implements DoCheck {
  ngDoCheck(): void {
    console.log('ngDoCheck executed');
  }
}
``` 

5. Run the app and navigate to the login page.
Observe the behavior of the ngDoCheck method and note unnecessary and repetitive executions.
Note: To stop unnecessary executions of ngDoCheck, comment out or remove the call to the initializeApp method in the app.component.ts file of the cloned project.

### Expected behavior

The expected behavior is for the ngDoCheck method to be called only when there are detected changes to a component's input properties or to events that occur within the component. In other words, it should only be run when there is a real need to check and take action based on the changes.

In the case of the problem you are experiencing, the expected behavior would be for the ngDoCheck method to be executed only when there are relevant changes to the login component, such as form data updates or authentication-related events. It should not run repeatedly for no apparent reason.

Commenting out or removing the call to the initializeApp method in the AppComponent component resolves the issue and the ngDoCheck method stops running repetitively, indicating that the source of the issue may be related to the initialization of the Capacitor Firebase Authentication library.

### Reproduction

https://github.com/robingenz/capacitor-firebase-authentication-demo

### Steps to reproduce

Clone the official Capacitor Firebase Authentication library demo project from the GitHub repository: https://github.com/robingenz/capacitor-firebase-authentication-demo

Open the login.page.ts file inside the login page folder (src/app/pages/login) in the cloned project.
Add the ngDoCheck method in the LoginPage class as follows:

1. Create a new Angular project with Capacitor.
2. Install and configure the Capacitor Firebase Authentication library according to the official documentation.
3. Implement authentication in the application using the methods and events provided by the library.
4. Observe the behavior of the ngDoCheck method and note unnecessary and repetitive executions.

```typescript
import { Component, DoCheck } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: 'login.page.html',
  styleUrls: ['login.page.scss'],
})
export class LoginPage implements DoCheck {
  ngDoCheck(): void {
    console.log('ngDoCheck executed');
  }
}
``` 

5. Run the app and navigate to the login page.
Observe the behavior of the ngDoCheck method and note unnecessary and repetitive executions.
Note: To stop unnecessary executions of ngDoCheck, comment out or remove the call to the initializeApp method in the app.component.ts file of the cloned project.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-06-24 06:03
Thank you for your request. I will take a look as soon as possible.

**Comment by robingenz** [comment] 2023-06-26 13:02
I could reproduce the issue without `@capacitor-firebase`, see: https://github.com/robingenz/capacitor-firebase-issue-390
Thus, this is not an issue caused by this library. For this reason I am closing this issue.

**Closed by robingenz** 2023-06-26 13:02 UTC
Labels: bug/fix, needs: triage, package: authentication
