### ISSUE TITLE
feat:  include firebase error in the Error thrown by createUserWithEmailAndPassword methods

### ISSUE THREAD

**Issue by dkkzzz** [capawesome-team/capacitor-firebase#350] opened 2023-03-31 10:33 UTC
**Is your feature request related to a problem? Please describe:**

When using firebase createUserWithEmailAndPassword method in device environment the error thrown will not give a way to retrieve the firebase error result which will give more information to the user

**Describe the solution you'd like:**

Add firebase exception error code on the exception thrown by the Plugin

**Describe alternatives you've considered:**

Add firebase exception error code on the exception thrown by the Plugin

**Additional context:**

**Comment by robingenz** [comment] 2023-03-31 10:47
I close this as duplicate of #25

**Closed by robingenz** 2023-03-31 10:47 UTC
Labels: duplicate
