### ISSUE TITLE
bug:  integration with angularfire

### ISSUE THREAD

**Issue by rodrigoGA** [capawesome-team/capacitor-firebase#361] opened 2023-04-14 00:30 UTC
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

get the authenticated user returns null

### Expected behavior

get authenticated user

### Reproduction

[example](https://github.com/rodrigoGA/capacitor-firebase-bug)

### Steps to reproduce

I am using this project in combination with angular fire and have been having some problems.
That I am not entirely clear about what is happening and I have my doubts about publishing the app in production.
In case I'm doing the correct steps and it's a problem I can take the trouble to create a sample project

The following is my project setup

package.json
  ```js
    "@angular/fire": "^7.5.0",
    "@capacitor-firebase/authentication": "^1.4.0",
    "@ionic/angular": "^7.0.0",
    "firebase": "^9.19.1",
  ```

main.ts
  ```js
const initFirebaseAuth = () => {
  if (Capacitor.isNativePlatform()) {
    return initializeAuth(getApp(), {
      persistence: indexedDBLocalPersistence
    });
  } else {
    return getAuth();
  }
};

...js
providers: [
	...
    importProvidersFrom(provideFirebaseApp(() => initializeApp(environment.firebase))),
    importProvidersFrom(provideAuth(() => initFirebaseAuth())),
    ...
]

  ```

maybe this file has nothing to do with the problem, but i read in the issues that it doesn't use angularfire and in combination with this plugin it's great.
<details>
  <summary>app.routes.ts </summary>

  ```js

import {
  redirectLoggedInTo,
  redirectUnauthorizedTo,
  canActivate
} from '@angular/fire/auth-guard';

const redirectUnauthorizedToLogin = () => redirectUnauthorizedTo(['login']);
const redirectLoggedInToHome = () => redirectLoggedInTo(['home']);
...
  {
    path: 'login',
    loadComponent: () => import('./pages/login/login.page').then( m => m.LoginPage),
    ...canActivate(redirectLoggedInToHome)
  },
  {
    path: 'home',
    loadComponent: () => import('./pages/home/home.page').then( m => m.HomePage),
    ...canActivate(redirectUnauthorizedToLogin)
  },
...

  ```
</details>

I have also declared skipNativeAuth: true and added the variable rgcfaIncludeGoogle = true in the android project.

According to the documentation to obtain the id token is the following way
```js
public async getCurrentUser ()  {
  const result = await FirebaseAuthentication.getCurrentUser();
  return result.user;
};

public async getIdToken () {
    const currentUser = await this.getCurrentUser();
    if (!currentUser) {
    	return null;
    }
    const result = await FirebaseAuthentication.getIdToken();
    return result.token;
}

```

From web it works fine, but native currentuser is null, and when getting the id token I get the error

`Error:  Error: No user is signed in. 
`

at this point I'm a bit confused because I can do the imports from
`import {  getAuth,  GoogleAuthProvider ... } from 'firebase/auth';` 
or from
`import {  getAuth,  GoogleAuthProvider ... } from'@angular/fire/auth';` 

but neither works on native devices

Carrying out tests I have found that the following code does work when it is packaged as an android application

```js
public async getIdToken () {
	const auth = getAuth();
	const currentUser = auth.currentUser;
	if (!currentUser) {
	  return null;
	}
	const token = await currentUser.getIdToken();
	return token;
};
```

Does this make sense?

### Other information

.

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.7.3
  @capacitor/core: 4.7.3
  @capacitor/android: 4.7.3
  @capacitor/ios: 4.7.3

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.7.1
  @capacitor/core: 4.7.1
  @capacitor/android: 4.7.1

[error] build.gradle file missing applicationId "io.ionic.starter" config in
       ..../android/app/build.gradle

### Before submitting

- [X] I understand that incomplete problems (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-04-14 06:08
You have to sign-in the user on the native and the web layer, see https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/firebase-js-sdk.md

Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository.

**Comment by rodrigoGA** [comment] 2023-04-14 22:48
I am using the exact same function recommended by the documentation to login with google.

Here is an example project https://github.com/rodrigoGA/capacitor-firebase-bug
On the web it works correctly, but on android it seems not to be logged in if the documentation guide is followed.

**Comment by robingenz** [comment] 2023-04-15 13:17
Unfortunately I can't reproduce your issue with your GitHub repo.
I can successfully log in to Google and then also get the Firebase user via the Firebase JS SDK:

![grafik](https://user-images.githubusercontent.com/13857929/232226162-55e18294-7ff0-4505-8a03-d3759b7e6a59.png)

Note that you cannot retrieve the Firebase user via the plugin, since you are using the `skipNativeAuth` config option.

**Comment by rodrigoGA** [comment] 2023-04-15 13:44
Authentication works fine, the issue is with obtaining the ID token once authenticated. 

Upon entering the home screen, the token is obtained in two ways: the one proposed by the documentation and another that works.

https://github.com/rodrigoGA/capacitor-firebase-bug/blob/master/src/app/pages/home/home.page.ts
```
    this.authService.getIdTokenAngularFirebase().then((token)=>{
      this.angularFireAuthToken = token;
    } );

    this.authService.getIdTokenCustom().then((token)=>{
      this.customFireAuthToken = token;
    } );
```

I don't know why this works
```
  public async getCurrentUserAngularFirebase ()  {
    const result = await FirebaseAuthentication.getCurrentUser();
    return result.user;
  };
```


the one proposed by the documentation doesn't
```
  public async getIdTokenAngularFirebase () {
    const currentUser = await this.getCurrentUserAngularFirebase();
    if (!currentUser) {
       return null;
    }
    const result = await FirebaseAuthentication.getIdToken();
    return result.token;
  }
```

Sorry for the messy code and variable names, they're not very representative, but I was very tired when I wrote it. When executing the function getIdTokenAngularFirebase, which is the way to obtain the token according to the documentation, an error will be thrown because there is no logged-in user, even though the login works fine, and subscribing to the user change event retrieves the logged-in user at the moment the login is performed. 

Please note that the issue occurs on a native device, I am testing it on Android. It works fine on the web.

**Comment by rodrigoGA** [comment] 2023-04-15 14:42
The issue I was facing was the inability to obtain the ID token once the user is authenticated using the function recommended by the documentation. This can be observed on the homepage, where getIdTokenAngularFirebase does not work, while getIdTokenCustom works fine (sorry for the unrepresentative names, I was a bit sleepy when I wrote them).

Regarding your comment, 

> Note that you cannot retrieve the Firebase user via the plugin, since you are using the skipNativeAuth config option

my understanding is that I need to use the skipNativeAuth option to integrate with AngularFire. When you say that I cannot retrieve the user natively, does it mean that the methods exposed in the documentation do not work when skipNativeAuth is used?

to be clearer

This doesn't work on android native (documentation way):
```
  public async getIdTokenAngularFirebase () {
    const currentUser = await this.getCurrentUserAngularFirebase();
    if (!currentUser) {
       return null;
    }
    const result = await FirebaseAuthentication.getIdToken();
    return result.token;
  }
```
This works
```
  public async getIdTokenCustom () {
    const auth = getAuth();
    const currentUser = auth.currentUser;
    if (!currentUser) {
      return null;
    }
    const token = await currentUser.getIdToken();
    return token;
  };
```
- is this the expected behavior?
- should I use skipNativeAuth to integrate with angularfire?
- Is the way I found to obtain the token correct?

**Comment by robingenz** [comment] 2023-04-15 14:53
As I said, you can't retrieve the Firebase user via the plugin because you're using the `skipNativeAuth` option, so you can't retrieve the ID token as well. For this you need to use the Firebase JS SDK.
So yes, this is the expected behavior.

> should I use skipNativeAuth to integrate with angularfire?

This depends on your use case.

I am closing this issue as the issue seems to be resolved and is not a bug with the plugin.

**Closed by robingenz** 2023-04-15 14:53 UTC
Labels: platform: android, bug/fix, needs: reproduction, needs: triage, package: authentication
