### ISSUE TITLE
bug: onNewToken and onMessageReceived methods not available in iOS

### ISSUE THREAD

**Issue by bharatAlcovex** [capawesome-team/capacitor-firebase#291] opened 2022-12-30 16:21 UTC
**Plugin(s):**

FirebaseMessaging

**Platform(s):**

iOS

**Current behavior:**

I want to modify the notification receive code in order to pass some custom business logic, In this I noticed that the FirebaseService methods exist in android only & not iOS. How can I access such methods and modify them accordingly.

**Expected behavior:**

Same methods should be available for both Android & ios

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

Installed Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/core: 4.6.1
  @capacitor/ios: 4.6.1
```

**Comment by robingenz** [comment] 2022-12-30 16:42
Have a look at:
https://github.com/capawesome-team/capacitor-firebase/blob/4d12fe2a7a2df367f3f679ba2e68d5c891541564/packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift#L150

I am closing this issue as it is not a bug in the plugin. Please ask questions in [dicussions](https://github.com/capawesome-team/capacitor-firebase/discussions) in the future.

**Closed by robingenz** 2022-12-30 16:42 UTC
Labels: needs: triage
