### ISSUE TITLE
bug: When Logging In With "Google", The ProviderId Says "Firebase"

### ISSUE THREAD

**Issue by aaronksaunders** [capawesome-team/capacitor-firebase#160] opened 2022-07-25 23:03 UTC
**Plugin(s):**
FirebaseAuthentication

**Platform(s):**
IOS

**Current behavior:**
```
  FirebaseAuthentication.getCurrentUser().then(user => console.log(user));
```
will log out the user, but displays the incorrect `providerId`, the correct id is provided in the `credential` object when signing in but you don't get the `credential` information when calling `FirebaseAuthentication.getCurrentUser()`

**Expected behavior:**
display the correct  `providerId`

**Steps to reproduce:**
```
  FirebaseAuthentication.getCurrentUser().then(user => console.log(user));
```

**Related code:**
```
  FirebaseAuthentication.getCurrentUser().then(user => console.log(user));
```

you can also see the same behavior when running the test application

**Other information:**
<img width="1367" alt="Screen Shot 2022-07-25 at 7 02 23 PM" src="https://user-images.githubusercontent.com/524953/180889010-70854694-a18c-415d-a548-ed1a4a82e539.png">

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
```

**Comment by robingenz** [comment] 2022-07-26 08:03
Hi @aaronksaunders,
please have a look at this SO answer: https://stackoverflow.com/a/39294811/6731412
You are looking for the `providerData` property which also has a `providerId` property with the value you want. This is currently not supported. I have created a feature request for this: #161 
Since this is not a bug I close the issue.

**Closed by robingenz** 2022-07-26 08:03 UTC
Labels: needs: triage
